var C={};
(function(){var b=C;(function(a,c){function d(a,c){return Object.prototype.toString.call(c)==="[object "+a+"]"?!0:!1}function e(a){return d("Object",a)}function f(a,c,d){var b;if(e(c)){for(b in c)a.setAttribute(b,c[b]);return!0}return d||""===d?a.setAttribute(c,d):a.getAttribute(c)}function g(a,c){for(var d=a.className,d=d?d.split(" "):[],e=0,b=d.length;e<b;e++)if(c&&c===d[e])return!0;return!1}function h(a,c){var d="";if(g(a,c))return!1;a.className&&(d=" ");a.className=a.className+d+c;return!0}function j(a,
c){var d,e=[],b,f;if(!g(a,c))return!1;d=a.className.split(" ");b=0;for(f=d.length;b<f;b++)c!==d[b]&&e.push(d[b]);a.className=e.join(" ");return!0}function i(a,c){var d=c.querySelectorAll(a),e=[],b,g;b=0;for(g=d.length;b<g;b++)e[b]=d[b];return e}function k(a){var c=""+a;return c.match("^{.*}$")?JSON.parse(c):c.match("^[0-9.]+$")?1*c:"true"===c?!0:"false"===c?!1:a}Date.now||(Date.now=function(){return+new Date});b.utility={win:a,doc:c,body:c.body,$:function(a){return c.querySelector(a)},$$:function(a){return i(a,
c)},$child:function(a,c){return c.querySelector(a)},$$child:i,$id:function(a){return c.getElementById(a)},pageTop:function(){a.scrollTo(0,1)},onEvent:function(a,c,d){a.addEventListener(c,d)},offEvent:function(a,c,d){a.removeEventListener(c,d)},makeElement:function(a,d){var b=c.createElement(a);d&&f(b,d);return b},showElement:function(a){a.style.display="block"},hideElement:function(a){a.style.display="none"},opacityElement:function(a,c){a.style.opacity=c},hasClass:g,addClass:h,removeClass:j,toggleClass:function(a,
c){return g(a,c)?j(a,c):h(a,c)},styleElement:function(a,c){var d=a.style,b,e,g;for(b in c){e=b;g=c[b];isFinite(g)&&(g=g+"px");d[e]=g}},computedStyleElement:function(a){return c.defaultView.getComputedStyle(a,null)},appendElement:function(a,c){a.appendChild(c)},attrElement:f,innerHTML:function(a,c){if(c)a.innerHTML=c;else return a.innerHTML},override:function(a,c){for(var d in c)a[d]=c[d];return a},replaceAll:function(a,c,d){return a.split(c).join(d)},windowOpen:function(c,d){return a.open(c,d)},typeCast:k,
makeQueryString:function(a){var c="",d="",b;for(b in a)if(a[b]){d=d+(c+b+"="+encodeURIComponent(a[b]));c="&"}return d},parseQueryString:function(a){var a=a.replace(/^\#/,"").replace(/^\?/,""),a=a.split("&"),c,d,b={};for(c=a.length;c--;){d=a[c].split("=");b[d[0]]=k(decodeURIComponent(d[1]))}return b},is:d,isObject:e,isNumber:function(a){return d("Number",a)},isString:function(a){return d("String",a)},isFunction:function(a){return d("Function",a)},isBoolean:function(a){return d("Boolean",a)},isTouchDevice:function(){return"ontouchstart"in
a},nullFunction:function(){return null}}})(window,document);b.klass=function(a){var c=b.utility.override,d=a.init||function(){},e=a.properties;(a=a.extend)&&b.extend(d,a);c(d.prototype,e);return d};b.extend=function(a,c){function d(){this.init=a}d.prototype=c.prototype;a.prototype=new d;var b=a.prototype;b._superclass=c;b._super=function(){var a=this._prevctor,a=a?a.prototype._superclass:this._prevctor=c;a.apply(this,arguments)}};b.selector=function(a,c){var d=b.selector,e=(c||document).querySelectorAll(a),
f,g=0,h=e.length;f=function(){};f.prototype=d.methods;d=new f;d.length=h;for(d.selector=a;g<h;g++)d[g]=e[g];return d};(function(){function a(a,c,b){for(var e=0,i=a.length,b=d(b);e<i;e++)b[0]=a[e],c.apply(null,b);return a}function c(a,c,b){b=d(b);b[0]=a[0];return c.apply(null,b)}function d(a){var c=[null];c.push.apply(c,a);return c}var e=b.utility;b.selector.methods={_forexe:a,_exe:c,_argary:d,querySelectorAll:function(a){return this[0].querySelectorAll(a)},find:function(a){return b.selector(a,this)},
on:function(){return a(this,e.onEvent,arguments)},off:function(){return a(this,e.offEvent,arguments)},show:function(){return a(this,e.showElement)},hide:function(){return a(this,e.hideElement)},opacity:function(){return a(this,e.opacityElement,arguments)},hasClass:function(){return c(this,e.hasClass,arguments)},addClass:function(){return a(this,e.addClass,arguments)},removeClass:function(){return a(this,e.removeClass,arguments)},toggleClass:function(){return a(this,e.toggleClass,arguments)},css:function(){return a(this,
e.styleElement,arguments)},html:function(){return c(this,e.innerHTML,arguments)},attr:function(){return c(this,e.attrElement,arguments)},append:function(){return a(this,e.appendElement,arguments)}}})();(function(){function a(a,e,j,i,k){d.isFunction(j)&&(k=j,j=null);d.isFunction(i)&&(k=i,i=null);var n=b.Tweener,l=a.style,m,a=d.computedStyleElement(a),o,p={};for(m in e)o=c(e[m]),p[m]={from:1*c(a.getPropertyValue(m))[1]||0,to:1*o[1]||0,suffix:o[2]};new n(l,p,{duration:j,easing:f[i],onComplete:k})}function c(a){return(""+
(a||"")).match(/^([0-9\.]+)(.*)/)}var d=b.utility,e=b.selector.methods,f={};b.easing&&(Easing=b.easing);d.override(e,{animate:function(){return e._forexe(this,a,arguments)}})})();b.easing={easeInCubic:function(a,c,d,b){return d*Math.pow(a/b,3)+c},easeOutCubic:function(a,c,d,b){return d*(Math.pow(a/b-1,3)+1)+c},easeInOutCubic:function(a,c,d,b){return 1>(a/=b/2)?d/2*Math.pow(a,3)+c:d/2*(Math.pow(a-2,3)+2)+c},easeInQuart:function(a,c,d,b){return d*Math.pow(a/b,4)+c},easeOutQuart:function(a,c,d,b){return-d*
(Math.pow(a/b-1,4)-1)+c},easeInOutQuart:function(a,c,d,b){return 1>(a/=b/2)?d/2*Math.pow(a,4)+c:-d/2*(Math.pow(a-2,4)-2)+c},easeInQuint:function(a,c,d,b){return d*Math.pow(a/b,5)+c},easeOutQuint:function(a,c,d,b){return d*(Math.pow(a/b-1,5)+1)+c},easeInOutQuint:function(a,c,d,b){return 1>(a/=b/2)?d/2*Math.pow(a,5)+c:d/2*(Math.pow(a-2,5)+2)+c},easeInSine:function(a,c,d,b){return d*(1-Math.cos(a/b*(Math.PI/2)))+c},easeOutSine:function(a,c,d,b){return d*Math.sin(a/b*(Math.PI/2))+c},easeInOutSine:function(a,
c,d,b){return d/2*(1-Math.cos(Math.PI*a/b))+c},easeInExpo:function(a,c,d,b){return d*Math.pow(2,10*(a/b-1))+c},easeOutExpo:function(a,c,d,b){return d*(-Math.pow(2,-10*a/b)+1)+c},easeInOutExpo:function(a,c,d,b){return 1>(a/=b/2)?d/2*Math.pow(2,10*(a-1))+c:d/2*(-Math.pow(2,-10*--a)+2)+c},easeInCirc:function(a,c,d,b){return d*(1-Math.sqrt(1-(a/=b)*a))+c},easeOutCirc:function(a,c,d,b){return d*Math.sqrt(1-(a=a/b-1)*a)+c},easeInOutCirc:function(a,c,d,b){return 1>(a/=b/2)?d/2*(1-Math.sqrt(1-a*a))+c:d/2*
(Math.sqrt(1-(a-=2)*a)+1)+c},easeInQuad:function(a,c,d,b){return d*(a/=b)*a+c},easeOutQuad:function(a,c,d,b){return-d*(a/=b)*(a-2)+c},easeInOutQuad:function(a,c,d,b){return 1>(a/=b/2)?d/2*a*a+c:-d/2*(--a*(a-2)-1)+c}};(function(){var a=b.utility.isTouchDevice();b.Event=b.klass({init:function(a){a=a||{};if(a.single&&b.Event.instance)return b.Event.instance;a.single&&(b.Event.instance=this)},properties:{utility:b.utility,switchclick:a?"touchstart":"click",switchdown:a?"touchstart":"mousedown",switchmove:a?
"touchmove":"mousemove",switchup:a?"touchend":"mouseup",load:"load",hashchange:"hashchange",click:"click",mousedown:"mousedown",mousemove:"mousemove",mouseup:"mouseup",touchstart:"touchstart",touchmove:"touchmove",touchend:"touchend",orientationchange:"orientationchange",resize:"resize"}});b.Event.instance=null})();b.HashController=b.klass({properties:{utility:b.utility,typeCast:function(a){var c=this.utility.typeCast(a);return a===c&&(a=a.match("^[\"'](.*)[\"']$"))?a[1]:c},makeHash:function(a){var c=
"#"+a.mode,a=a.vars,d="?",b;for(b in a)c+=d+b+"="+JSON.stringify(a[b]),d="&";return encodeURI(c)},setHash:function(a){location.hash=this.makeHash(a);return!0},parseHash:function(a){var c,d,b,f;c=decodeURIComponent(a).split("#")[1];if(!c)return!1;c=c.split("?");a=c[0];if(c[1]){d={};c=c[1].split("&");for(f=c.length;f--;)c[f]&&(b=c[f].split("="),d[b[0]]=this.typeCast(b[1]))}return{mode:a,vars:d}},getHash:function(){return this.parseHash(location.hash)}}});b.Ajax=b.klass({init:function(){this.xhr=new XMLHttpRequest},
properties:{utility:b.utility,request:function(a){var c=a.url,d=a.callback,b=a.error,f=a.type||"GET",g="",h;a.cash||(a.query||(a.query={}),a.query["ajaxcash"+Date.now()]="0");a.query&&(g=this.utility.makeQueryString(a.query),g=encodeURI(g));h=this.xhr=new XMLHttpRequest;h.onreadystatechange=function(){if(h.readyState!=4)return false;h.status==200?d(h.responseText):b&&b(h)};h.open(f,c);"POST"===f&&h.setRequestHeader("Content-Type","application/x-www-form-urlencoded");h.send(g)},abort:function(){this.xhr.abort()},
getJSON:function(a){this.request({type:a.type,url:a.url,callback:function(c){a.callback(JSON.parse(c))},error:function(c){a.error&&a.error(c)}})}}});b.Bind=b.klass({properties:{utility:b.utility,add:function(a){return this.exe(a,!0)},remove:function(a){return this.exe(a,!1)},exe:function(a,c){var b=this.utility,e=a.element,f=a.events,b=c?b.onEvent:b.offEvent,g;for(g in f)b(e,g,f[g]);return a}}});(function(){var a=b.utility.makeElement;b.CanvasImage=function(c){var b=a("canvas"),e=a("img"),f=c.src,
g=c.width,h=c.height,j=c.onload;e.onload=function(){b.width=g;b.height=h;b.getContext("2d").drawImage(e,0,0);j(b,e)};e.src=f;return b}})();b.CanvasRender=b.klass({init:function(a){this.canvas=a.canvas;this.ctx=this.canvas.getContext("2d");this.canvasWidth=this.canvas.width;this.canvasHeight=this.canvas.height;this.setSize(a)},properties:{setSize:function(a){a.width&&(this.canvas.width=this.canvasWidth=a.width);a.height&&(this.canvas.height=this.canvasHeight=a.height)},draw:function(a){this.ctx.clearRect(0,
0,this.canvasWidth,this.canvasHeight);for(var c=0,b=a.length,e;c<b;c++)e=a[c],this.ctx.drawImage(e.image,e.x,e.y)}}});b.DataStore=b.klass({init:function(a){a=a||{};if(a.single&&b.DataStore.instance)return b.DataStore.instance;this.data={};a.single&&(b.DataStore.instance=this)},properties:{set:function(a,c){this.data[a]=c;return!0},get:function(a){var c=this.data;if(a)return c[a];var a={},b;for(b in c)a[b]=c[b];return a},remove:function(a){var c=this.data;if(!c[a])return!1;delete c[a];return!0},reset:function(){this.data=
{};return!0}}});b.DataStore.instance=null;b.DragFlick=b.klass({init:function(a){a&&this.bind(a)},properties:{utility:b.utility,_event:new b.Event,_getEventTarget:function(a){return a.changedTouches?a.changedTouches[0]:a},amount:function(a){var c=this,b,e,f=!1;c.utility.onEvent(a.element,c._event.switchdown,function(a){var h=c._getEventTarget(a);b=h.pageX;e=h.pageY;f=!0;a.preventDefault()});c.utility.onEvent(c.utility.win,c._event.switchup,function(g){f&&(g=c._getEventTarget(g),a.callback({x:g.pageX-
b,y:g.pageY-e}),f=!1)})},direction:function(a){this.amount({element:a.element,callback:function(c){var b=a.boundary||0,e={change:!1,top:!1,right:!1,bottom:!1,left:!1,amount:c};Math.abs(c.x)>b&&(0<c.x?e.right=!0:0>c.x&&(e.left=!0),e.change=!0);Math.abs(c.y)>b&&(0<c.y?e.bottom=!0:0>c.y&&(e.top=!0),e.change=!0);a.callback(e)}})},bind:function(a){function c(a,c,e){g.onEvent(a,c,function(a){a=b._getEventTarget(a);e(a)})}var b=this,e=a.element,f=this._event,g=this.utility,h=a.start||g.nullFunction,j=a.move||
g.nullFunction,i=a.end||g.nullFunction,k=!1,n=0,l=0;a.direction&&b.direction({element:e,boundary:a.boundary,callback:a.direction});c(e,f.switchdown,function(a){k=!0;n=a.pageX;l=a.pageY;h({e:a,move:{x:n,y:l}})});c(g.doc,f.switchmove,function(a){k&&j({e:a,move:{x:a.pageX-n,y:a.pageY-l}})});c(g.doc,f.switchup,function(a){k&&(i({e:a,move:{x:a.pageX-n,y:a.pageY-l}}),k=!1)})}}});b.ExternalInterface=function(a){var a=a||{},c;if(a.single&&b.ExternalInterface.instance)return b.ExternalInterface.instance;c=
a.android?new b.ExternalInterface.Android(a):new b.ExternalInterface.IOS(a);a.single&&(b.ExternalInterface.instance=c);return c};b.ExternalInterface.instance=null;b.ExternalInterface.Android=b.klass({init:function(a){a=a||{};this.android=a.android;this.externalObj=a.externalObj;this.externalObj||(b.EXTERNAL_ANDROID={},this.externalObj=b.EXTERNAL_ANDROID)},properties:{hashCtrl:new b.HashController,call:function(a){this.android[a.mode](this.hashCtrl.makeHash(a))},addCallback:function(a,c){var b=this;
b.externalObj[a]=function(a){a=b.hashCtrl.parseHash(a);return c(a.vars)}},removeCallback:function(a){delete this.externalObj[a]}}});b.ExternalInterface.IOS=b.klass({init:function(){this.ios={}},properties:{utility:b.utility,_event:new b.Event,hashCtrl:new b.HashController,call:function(a){this.hashCtrl.setHash(a)},addCallback:function(a,c){var b=this;b.ios[a]=function(){var e=b.hashCtrl.getHash();return e.mode===a?(c(e.vars),!0):!1};this.utility.onEvent(this.utility.win,this._event.hashchange,this.ios[a])},
removeCallback:function(a){this.utility.offEvent(this.utility.win,this._event.hashchange,this.ios[a]);delete this.ios[a]}}});b.Facebook=b.klass({properties:{utility:b.utility,shareURLBase:"https://www.facebook.com/dialog/feed?",getShareURL:function(a){var c=this.shareURLBase+"app_id="+a.app_id+"&redirect_uri="+a.redirect_uri;return c+=this.utility.makeQueryString({link:a.link,picture:a.picture,name:a.name,caption:a.caption,description:a.description})}}});(function(){function a(b){b.nexttime<=Date.now()&&
(c(b),b.nexttime=b.nowtime+b.msecFrame);1===b.loopid&&f(function(){a(b)})}function c(a){a.nowtime=Date.now();a.surver=Math.round(1E3/(a.nowtime-a.prevtime));a.prevtime=a.nowtime;a.enter()}var d,e=b.utility.win,f=e.requestAnimationFrame||e.webkitRequestAnimationFrame||e.mozRequestAnimationFrame||e.oRequestAnimationFrame||e.msRequestAnimationFrame||!1;b.FPS=b.klass({init:function(a){a=a||{};a.criterion||(a.criterion=20);if(a.single&&d)return d;this.surver=this.criterion=a.criterion;this.enterframe=
a.enterframe;this.msecFrame=Math.round(1E3/this.criterion);this.prevtime=this.nowtime=this.nexttime=this.loopid=0;a.single&&(d=this)},properties:{getCriterion:function(){return this.criterion},getSurver:function(){return this.surver},getFrameTime:function(){return this.msecFrame},enter:function(){this.enterframe({criterion:this.criterion,surver:this.surver})},start:function(){this.prevtime=Date.now();this.nexttime=this.prevtime+this.msecFrame;f?(this.loopid=1,a(this)):this.loopid=setInterval(c,this.msecFrame,
this)},stop:function(){clearInterval(this.loopid);this.loopid=0}}})})();b.ImgLoad=b.klass({init:function(a){var c=this;c.srcs=a.srcs;c.srccount=c.srcs.length;c.loadedsrcs=[];c.onload=a.onload||c.utility.nullFunction;c.onprogress=a.onprogress||c.utility.nullFunction;c.loadcount=0;c.progress=0;c.check=function(){c.loadcount++;c.progress=c.loadcount/c.srccount;c.onprogress(c.progress);if(c.loadcount>=c.srccount)c.onload(c.loadedsrcs)}},properties:{utility:b.utility,_event:new b.Event,start:function(){var a,
c,b;c=0;for(b=this.srccount;c<b;c++)a=this.utility.makeElement("img"),a.src=this.srcs[c],this.utility.onEvent(a,this._event.load,this.check),this.loadedsrcs.push(a)},getProgress:function(){return this.progress}}});b.Loading=b.klass({init:function(a){if(a&&a.onload)this.onload(a.onload)},properties:{utility:b.utility,_event:new b.Event,onload:function(a){this.utility.onEvent(this.utility.win,this._event.load,a)}}});b.LocalStorage=b.klass({init:function(a){a=a||{};if(a.single&&b.LocalStorage.instance)return b.LocalStorage.instance;
a.single&&(b.LocalStorage.instance=this)},properties:{utility:b.utility,storage:b.utility.win.localStorage,set:function(a,c){this.storage.setItem(a,JSON.stringify(c));return!0},get:function(a){if(a)return JSON.parse(this.storage.getItem(a));var a={},c;for(c in this.storage)a[c]=JSON.parse(this.storage[c]);return a},remove:function(a){if(!this.storage.getItem(a))return!1;this.storage.removeItem(a);return!0},reset:function(){this.storage.clear();return!0}}});b.LocalStorage.instance=null;(function(){function a(a){a.preventDefault();
return!1}function c(a,c){a=a?a:f;return a.match(c)?!0:!1}function d(){0===win.pageYOffset&&this.utility.pageTop()}function e(){setTimeout(d,100)}var f=navigator.userAgent;b.Mobile=b.klass({properties:{utility:b.utility,_event:new b.Event,isAndroid:function(a){return c(a,/Android/i)},isIOS:function(a){return c(a,/iPhone|iPad|iPod/i)},isWindows:function(a){return c(a,/IEMobile/i)},isFBAPP:function(a){return c(a,/FBAN/)},isMobile:function(){return this.isAndroid()||this.isIOS()||this.isWindows()||this.isFBAPP()},
killScroll:function(c){c||this.utility.pageTop();this.utility.onEvent(this.utility.doc,this._event.touchmove,a)},revivalScroll:function(c){c||this.utility.pageTop();this.utility.offEvent(this.utility.doc,this._event.touchmove,a)},hideAddress:function(){this.utility.onEvent(this.utility.win,this._event.load,e,!1);this.utility.onEvent(this.utility.win,this._event.orientationchange,e,!1)},orientationCheck:function(){return 90!==Math.abs(this.utility.win.orientation)&&this.utility.win.innerWidth<this.utility.win.innerHeight?
{portrait:!0,landscape:!1}:{portrait:!1,landscape:!0}},orientationChange:function(a){function c(a,b){a(e.utility.win,e._event.load,b);a(e.utility.win,e._event.orientationchange,b);a(e.utility.win,e._event.resize,b)}function b(){d();c(e.utility.offEvent,b)}function d(){if(e.orientationCheck().portrait)return a.portrait(),!0;a.landscape()}var e=this;a.immediately&&d();if(a.one)return c(e.utility.onEvent,b),function(){c(e.utility.offEvent,b)};c(e.utility.onEvent,d);return function(){c(e.utility.offEvent,
d)}}}})})();b.NumberImage=b.klass({init:function(a){a=a||{type:""};this.type=a.type},properties:{make:function(a){var a=(""+a).split(""),c="",b;for(b=a.length;b--;)c='<span class="num_'+(this.type+a[b])+'">&nbsp;</span>'+c;return c}}});b.Observer=b.klass({init:function(a){a=a||{single:!1};if(a.single&&b.Observer.instance)return b.Observer.instance;this.observed={};a.single&&(b.Observer.instance=this)},properties:{getObserved:function(){return this.observed},on:function(a,c){var b=this.observed;b[a]||
(b[a]=[]);b[a].push(c)},one:function(a,c){var b=this,e=function(f){c(f);b.off(a,e)};b.on(a,e)},off:function(a,c){var b=this.observed;if(!c)return delete b[a],!0;var e=b[a],f;if(!e)return!1;for(f=e.length;f--;)if(c===e[f])return e.splice(f,1),0===e.length&&delete b[a],!0;return!1},fire:function(a,c){var b=this.observed[a],e,f;if(!b)return!1;for(f=b.length;f--;)(e=b[f])&&e(c);return!0}}});b.Observer.instance=null;b.PreRender=b.klass({init:function(a){a=a||{};a.loopblur||(a.loopblur=20);this.elements=
a.elements||[];this.guesslimit=a.guesslimit||30;this.onrendered=a.onrendered||this.utility.nullFunction;this.looptime=a.looptime||100;this.loopblur=this.looptime+a.loopblur;this.loopid=this.prevtime=null},properties:{utility:b.utility,start:function(){var a;for(a=this.elements.length;a--;)this.utility.showElement(this.elements[a]);this.prevtime=Date.now();this.loopid=setInterval(function(a){var b=Date.now(),e=b-a.prevtime;a.prevtime=b;if(e<a.loopblur&&(a.guesslimit--,1>a.guesslimit)){clearInterval(a.loopid);
for(b=a.elements.length;b--;)a.utility.hideElement(a.elements[b]);a.onrendered()}},this.looptime,this)}}});b.ScriptLoad=b.klass({properties:{utility:b.utility,_event:new b.Event,requests:function(a){for(var c=0,b=a.length;c<b;c++)this.request(a[c])},request:function(a){var b=this.utility.makeElement("script");b.type="text/javascript";b.src=a.src;this.utility.body.appendChild(b);if(a.callback)this.utility.onEvent(b,this._event.load,a.callback)}}});(function(){function a(a){return e?d.getResponseHeader(a):
!1}function c(a){var b=new XMLHttpRequest;b.onload=function(){a(b)};b.open("HEAD",location.href+"?update"+Date.now()+"=1");b.send(null);return b}var d,e=!1;b.ServerMeta=b.klass({init:function(a){var a=a||{},b=a.callback||this.utility.nullFunction;d?b(d):d=c(function(){e=!0;b(d)})},properties:{utility:b.utility,date:function(a){return c(function(b){b=new Date(b.getResponseHeader("Date"));a(b)})},connection:function(){return a("Connection")},contentLength:function(){return a("Content-Length")},lastModified:function(){return a("Last-Modified")},
server:function(){return a("Server")},contentType:function(){return a("Content-Type")},acceptRanges:function(){return a("Accept-Ranges")},keepAlive:function(){return a("Keep-Alive")}}})})();b.SessionStorage=b.klass({init:function(a){a=a||{};if(a.single&&b.SessionStorage.instance)return b.SessionStorage.instance;a.single&&(b.SessionStorage.instance=this)},properties:{utility:b.utility,storage:b.utility.win.sessionStorage,set:function(a,b){this.storage.setItem(a,JSON.stringify(b));return!0},get:function(a){if(a)return JSON.parse(this.storage.getItem(a));
var a={},b;for(b in this.storage)a[b]=JSON.parse(this.storage[b]);return a},remove:function(a){if(!this.storage.getItem(a))return!1;this.storage.removeItem(a);return!0},reset:function(){this.storage.clear();return!0}}});b.SessionStorage.instance=null;b.Surrogate=b.klass({init:function(a){this.delay=a.delay;this.callback=a.callback;this.waitid=this.args=null},properties:{request:function(a){this.args=a;this.clear();this.waitid=setTimeout(this.flush,this.delay,this)},flush:function(a){a=a||this;a.callback(a.args)},
clear:function(){clearInterval(this.waitid)}}});b.Throttle=b.klass({init:function(a){this.waittime=a.waittime;this.callback=a.callback;this.locked=!1;this.waitid=null},properties:{request:function(a){if(this.locked)return!1;this.callback(a);this.lock();this.waitid=setTimeout(this.unlock,this.waittime,this)},lock:function(){this.locked=!0},unlock:function(a){a=a||this;a.locked=!1;clearInterval(a.waitid)}}});b.Timer=function(a){function b(){m=Date.now();var a=g-(m-l)/1E3;0>a&&(a=0);p=d(a);i(p);if(m>
o)return r.stop(),k(),!0;q=setTimeout(b,j);return!1}function d(a){var b;b=(""+a).split(".");a=b[0];b=b[1]?b[1]:"";a=e({num:a,digit:n.integer});b=e({num:b,digit:n.few,isFew:!0});return a+"."+b}function e(a){var b=""+a.num,c=a.digit,d=c-b.length;return!a.isFew?-1<d?f(d,0)+b:f(c,9):0<d?b+f(d,0):b.slice(0,c)}function f(a,b){for(var c="",b=""+b;0<a;)c+=b,a--;return c}var g=a.limit,h=1E3*g,j=1E3*a.interval,i=a.onupdate,k=a.ontimeup,n=function(a){a=a.split(".");return{integer:a[0].length,few:a[1].length}}(a.template),
l=0,m=0,o=h,p=d(g),q,r={getLimit:function(){return g},getTime:function(){return p},getProgress:function(){return 1-(o-m)/h},setUpdate:function(a){i=a},setTimeup:function(a){k=a},countDown:function(){m=l=Date.now();o=l+h;b()},stop:function(){clearInterval(q)}};return r};b.Tweener=b.klass({init:function(a,c,d){var e,d=d||{};this.target=a;this.property=[];for(e in c)a=c[e],a.name=e,a.distance=a.to-a.from,a.prefix=a.prefix||"",a.suffix=a.suffix||"px",this.property.push(a);this.duration=d.duration||b.Tweener.Duration;
this.easing=d.easing||this._easing;this.onComplete=d.onComplete;this.begin=Date.now();b.Tweener.Items.push(this);b.Tweener.timerId||this.start()},properties:{_easing:function(a,b,d,e){return d*a/e+b},_requestAnimationFrame:function(){var a=b.utility.win,c=a.requestAnimationFrame||a.webkitRequestAnimationFrame||a.mozRequestAnimationFrame||a.oRequestAnimationFrame||a.msRequestAnimationFrame||!1;if(c)switch(c){case a.requestAnimationFrame:return function(a){requestAnimationFrame(a)};case a.webkitRequestAnimationFrame:return function(a){webkitRequestAnimationFrame(a)};
case a.mozRequestAnimationFrame:return function(a){mozRequestAnimationFrame(a)};case a.oRequestAnimationFrame:return function(a){oRequestAnimationFrame(a)};case a.msRequestAnimationFrame:return function(a){msRequestAnimationFrame(a)};default:return function(a){setTimeout(a,1E3/b.Tweener.FPS)}}}(),loop:function(){for(var a=this,c=b.Tweener.Items,d,e=Date.now(),f,g=c.length,h,j,i;g--;)if(d=c[g],j=d.property.length,f=e-d.begin,f<d.duration)for(h=0;h<j;h++)i=d.property[h],b.Tweener._setProp(d.target,
i,d.easing(f,i.from,i.distance,d.duration));else{for(h=0;h<j;h++)i=d.property[h],b.Tweener._setProp(d.target,i,i.to);if(d.onComplete)d.onComplete();c.splice(g,1)}if(c.length)return a._requestAnimationFrame(function(){a.loop()}),!0;this.end()},start:function(){var a=this;b.Tweener.timerId=1;a._requestAnimationFrame(function(){a.loop()})},end:function(){b.Tweener.Items=[];clearInterval(b.Tweener.timerId);b.Tweener.timerId=null}}});b.Tweener._setProp=function(a,b,d){a[b.name]=b.prefix+d+b.suffix};b.Tweener.timerId=
null;b.Tweener.Items=[];b.Tweener.FPS=30;b.Tweener.Duration=500;b.Twitter=b.klass({properties:{utility:b.utility,shareURLBase:"https://twitter.com/intent/tweet?",getShareURL:function(a){var b=a.redirect_uri,d=a.caption||"",e=a.name||"",a=a.hash||"",f=this.shareURLBase;return f+=this.utility.makeQueryString({url:b,text:d+(e?" \u300c"+e+"\u300d":"")+(a?" "+a:"")})}}});b.XML=b.klass({init:function(a){this.element=this.utility.makeElement("div");this.data={};a&&a.data&&this.setData(a.data)},properties:{utility:b.utility,
getData:function(){return this.data},setData:function(a){this.data=this.element.innerHTML=a},$:function(a){return this.utility.$child(a,this.element)},$$:function(a){return this.utility.$$child(a,this.element)}}})})();
