var Global={};
(function(a,e){function b(d,c){var a=c.querySelectorAll(d),e=[],b,i;b=0;for(i=a.length;b<i;b++)e[b]=a[b];return e}Date.now||(Date.now=function(){return+new Date});Global.utility={win:a,doc:e,body:e.querySelector("body"),$:function(d){return e.querySelector(d)},$$:function(d){return b(d,e)},$child:function(d,c){return c.querySelector(d)},$$child:b,$id:function(d){return e.getElementById(d)},onEvent:function(d,c,a){d.addEventListener(c,a)},offEvent:function(d,c,a){d.removeEventListener(c,a)},createElement:function(d){return e.createElement(d)},
showElement:function(d){d.style.display="block"},hideElement:function(d){d.style.display="none"},override:function(d,c){for(var a in c)d[a]=c[a];return d},replaceAll:function(a,c,b){a=a.split(c);return a=a.join(b)},windowOpen:function(d,c){return a.open(d,c)},parseQueryString:function(a){var c,b,e,h={},a=a.replace(/^\#/,""),a=a.replace(/^\?/,""),a=a.split("&");c=0;for(b=a.length;c<b;c++){e=a[c].split("=");h[e[0]]=decodeURIComponent(e[1])}return h}};console.log(Global.utility.parseQueryString("#?test=1&test2=a"))})(window,
document);Global.Ajax=function(){var a;return{request:function(e){var b=e.url,d=e.callback;e.cash||(b=b.match(/\?/)?b+"&":b+"?",b+="ajaxcash"+Date.now()+"=0");a=new XMLHttpRequest;a.onload=function(){d(a.responseText)};a.open("GET",b);a.send(null)},abort:function(){a.abort()}}};
Global.CanvasImage=function(a){var e=Global.utility.createElement,b=a.src,d=a.width,c=a.height,f=a.onload,g=e("img"),h=e("canvas");g.onload=function(){h.width=d;h.height=c;h.getContext("2d").drawImage(g,0,0);f(h,g)};g.src=b;return h};
Global.CanvasRender=function(a){var e=a.canvas,b=e.getContext("2d"),d=e.width,c=e.height,f={setSize:function(a){a.width&&(d=a.width,e.width=d);a.height&&(c=a.height,e.height=c)},draw:function(a){b.clearRect(0,0,d,c);g=0;for(h=a.length;g<h;g++)i=a[g],b.drawImage(i.image,i.x,i.y)}},g,h,i;f.setSize(a);return f};
Global.DataStore=function(a){var e=Global.DataStore,b=Global.utility.override,d,a=b({single:!1},a);if(a.single&&e.instance)return e.instance;d={};b={setData:function(a,b){d[a]=b;return!0},getData:function(a){if(a)return d[a];var a={},b;for(b in d)a[b]=d[b];return a},resetData:function(){d={};return!0}};a.single&&(e.instance=b);return b};
Global.Event=function(a){var e=Global.Event,b=Global.utility.override,a=b({single:!1,isMobile:function(){return!1}},a);if(a.single&&e.instance)return e.instance;b={click:"click",mousedown:"mousedown",mousemove:"mousemove",mouseup:"mouseup"};a.isMobile()&&(b.click="touchstart",b.mousedown="touchstart",b.mousemove="touchmove",b.mouseup="touchend");a.single&&(e.instance=b);return b};
Global.ExternalInterface=function(a){var e=!1,b=null,d=null,c=new Global.HashController;a||(a={});a.android?(e=!0,b=a.android,Global.EXTERNAL={}):d={};return function(){var a;a=e?{call:function(a){b[a.mode](c.makeHash(a))},addCallback:function(a,b){Global.EXTERNAL[a]=function(a){a=c.parseHash(a);return b(a.vars)}},removeCallback:function(a){delete Global.EXTERNAL[a]}}:{call:function(a){c.setHash(a)},addCallback:function(a,b){d[a]=function(){var d=c.getHash();if(d.mode===a){b(d.vars);return true}return false};
window.addEventListener("hashchange",d[a])},removeCallback:function(a){window.removeEventListener("hashchange",d[a]);delete d[a]}};a.isAndroid=function(){return e};return a}()};
Global.Facebook=function(){return{getShareURL:function(a){function e(a,b){b&&(g+="&"+a+"="+encodeURI(b))}var b=a.picture,d=a.name,c=a.caption,f=a.description,g="https://www.facebook.com/dialog/feed?app_id="+a.app_id+"&redirect_uri="+a.redirect_uri;e("link",a.link);e("picture",b);e("name",d);e("caption",c);e("description",f);return g}}};
Global.FPS=function(a){function e(){n++;n===o&&(n=0,b());1===k&&p(e)}function b(){l=Date.now();g=Math.round(1E3/(l-j));j=l;m.enter()}var d=Global.FPS,c=Global.utility.override,a=c({single:!1,criterion:20},a);if(a.single&&d.instance)return d.instance;var c=Global.utility.win,f=a.criterion,g=f,h=a.enterframe,i=Math.round(1E3/f),j,l,k,m={getCriterion:function(){return f},getSurver:function(){return g},getFrameTime:function(){return i},enter:function(){h({criterion:f,surver:g})},start:function(){j=Date.now();
p?(k=1,e()):k=setInterval(b,i)},stop:function(){clearInterval(k);k=0}},n=0,o=Math.round(60/f)+1,p=c.requestAnimationFrame||c.webkitRequestAnimationFrame||c.mozRequestAnimationFrame||c.oRequestAnimationFrame||c.msRequestAnimationFrame||!1;a.single&&(d.instance=m);return m};
Global.HashController=function(){var a={makeHash:function(a){var b="#"+a.mode,a=a.vars,d="?",c;for(c in a)b+=d+c+"="+JSON.stringify(a[c]),d="&";return encodeURI(b)},setHash:function(e){location.hash=a.makeHash(e);return!0},parseHash:function(a){var b,d=null;b=decodeURI(a).split("#")[1];if(!b)return!1;b=b.split("?");a=b[0];if(b[1]){d={};b=b[1].split("&");for(var c,f=b.length;f--;)b[f]&&(c=b[f].split("="),d[c[0]]=c[1].match("^{.*}$")?JSON.parse(c[1]):c[1].match("^[0-9.]+$")?1*c[1]:"true"===c[1]?!0:
"false"===c[1]?!1:c[1].match("^[\"'](.*)[\"']$")?c[1].match("^[\"'](.*)[\"']$")[1]:c[1]);return{mode:a,vars:d}}return{mode:a}},getHash:function(){return a.parseHash(location.hash)}};return a};Global.ImgLoad=function(a){var e=a.srcs,b=e.length,d=a.onload,c=0,f={start:function(){var a,c;for(c=b;c--;)a=new Image,a.src=e[c],a.onload=f.completeCheck},completeCheck:function(){c++;c>=b&&d()}};return f};
Global.Loading=function(a){var e=Global.utility.win,b={onload:function(a){e.addEventListener("load",a)}};if(a&&a.onload)b.onload(a.onload);return b};
Global.Mobile=function(){function a(a){a.preventDefault();return!1}function e(){c.scrollTo(0,1)}function b(a,b){a=a?a:i;return a.match(b)?!0:!1}var d=Global.utility,c=d.win,f=d.doc,g=d.onEvent,h=d.offEvent,i=navigator.userAgent,j={isAndroid:function(a){return b(a,/Android/i)},isIOS:function(a){return b(a,/iPhone|iPad|iPod/i)},isWindows:function(a){return b(a,/IEMobile/i)},isMobile:function(){return j.isAndroid()||j.isIOS()||j.isWindows()},scrollTop:e,killScroll:function(){e();g(f,"touchmove",a)},
revivalScroll:function(){e();h(f,"touchmove",a)},hideAddress:function(){function a(){0===c.pageYOffset&&e()}function b(){setTimeout(a,100)}g(c,"load",b,!1);g(c,"orientationchange",b,!1)},orientationCheck:function(){return 90!==Math.abs(c.orientation)&&c.innerWidth<c.innerHeight?{portrait:!0,landscape:!1}:{portrait:!1,landscape:!0}},orientationChange:function(a){function b(a,d){a(c,"load",d);a(c,"orientationchange",d);a(c,"resize",d)}function d(){e();b(h,d)}function e(){if(j.orientationCheck().portrait)return a.portrait(),
!0;a.landscape()}a.immediately&&e();if(a.one)return b(g,d),function(){b(h,d)};b(g,e);return function(){b(h,e)}}};return j};Global.NumberImage=function(a){var e=a.type;e||(e="");return{make:function(a){var a=(""+a).split(""),d="",c;for(c=a.length;c--;)d='<span class="num_'+e+a[c]+'">&nbsp;</span>'+d;return d}}};
Global.Observer=function(a){var e=Global.Observer,b=Global.utility.override,a=b({single:!1},a);if(a.single&&e.instance)return e.instance;var d={},c={getObserved:function(){return d},on:function(a,b){d[a]||(d[a]=[]);d[a].push(b)},forOn:function(a){for(var b in a)c.on(b,a[b])},one:function(a,b){wrapfunc=function(d){b(d);c.off(a,wrapfunc)};c.on(a,wrapfunc)},off:function(a,b){if(!b)return delete d[a],!0;var c=d[a],e;if(!c)return!1;for(e=c.length;e--;)if(b===c[e])return c.splice(e,1),0===c.length&&delete d[a],
!0;return!1},forOff:function(a){for(var b in a)c.off(b,a[b])},fire:function(a,b){var c=d[a],e,j;if(!c)return!1;for(j=c.length;j--;)(e=c[j])&&e(b);return!0}};a.single&&(e.instance=c);return c};
Global.PreRender=function(a){function e(){var a=Date.now(),b=a-k;k=a;if(b<j&&(g--,1>g)){clearInterval(l);for(a=f.length;a--;)c(f[a]);h()}}var b=Global.utility,b=b.override,a=b({elements:[],guesslimit:30,looptime:100,loopblur:20,onrendered:function(){}},a),b=Global.utility,d=b.showElement,c=b.hideElement,f=a.elements,g=a.guesslimit,h=a.onrendered,i=a.looptime,j=i+a.loopblur,l,k;return{start:function(){for(var a=f.length;a--;)d(f[a]);k=Date.now();l=setInterval(e,i)}}};
Global.Proxy=function(a){var e=a.delay,b=a.callback,d,c,f={request:function(a){d=a;f.clear();c=setTimeout(f.flush,e)},flush:function(){b(d)},clear:function(){clearInterval(c)}};return f};
Global.Timer=function(a){function e(){m=Date.now();var a=f-(m-k)/1E3;0>a&&(a=0);o=b(a);i(o);if(m>n)return q.stop(),j(),!0;p=setTimeout(e,h);return!1}function b(a){var b;b=(""+a).split(".");a=b[0];b=b[1]?b[1]:"";a=d({num:a,digit:l.integer});b=d({num:b,digit:l.few,isFew:!0});return a+"."+b}function d(a){var b=""+a.num,d=a.digit,e=d-b.length;return!a.isFew?-1<e?c(e,0)+b:c(d,9):0<e?b+c(e,0):b.slice(0,d)}function c(a,b){for(var c="",b=""+b;0<a;)c+=b,a--;return c}var f=a.limit,g=1E3*f,h=1E3*a.interval,
i=a.onupdate,j=a.ontimeup,l=function(a){a=a.split(".");return{integer:a[0].length,few:a[1].length}}(a.template),k=0,m=0,n=g,o=b(f),p,q={getLimit:function(){return f},getTime:function(){return o},getProgress:function(){return 1-(n-m)/g},setUpdate:function(a){i=a},setTimeup:function(a){j=a},countDown:function(){m=k=Date.now();n=k+g;e()},stop:function(){clearInterval(p)}};return q};
Global.Twitter=function(){return{getShareURL:function(a){var e=a.redirect_uri,b=a.caption||"",d=a.name||"",c=a.hash||"",a="https://twitter.com/intent/tweet?";d&&(d=" \u300c"+d+"\u300d");c&&(c=" "+c);e&&(a+="&url="+encodeURIComponent(e));(e=b+d+c)&&(a+="&text="+encodeURIComponent(e));return a}}};
Global.XML=function(a){var e=Global.utility,b=e.$child,d=e.$$child,c=e.createElement("div"),f=a.data;f&&(c.innerHTML=f);return{getData:function(){return f},setData:function(a){f=c.innerHTML=a},$:function(a){return b(a,c)},$$:function(a){return d(a,c)}}};
