var Global={};
(function(d,b){function f(c,a){var g=a.querySelectorAll(c),d=[],b,e;b=0;for(e=g.length;b<e;b++)d[b]=g[b];return d}function e(c){var a=""+c;return a.match("^{.*}$")?JSON.parse(a):a.match("^[0-9.]+$")?1*a:"true"===a?!0:"false"===a?!1:c}Date.now||(Date.now=function(){return+new Date});Global.utility={win:d,doc:b,body:b.body,$:function(c){return b.querySelector(c)},$$:function(c){return f(c,b)},$child:function(c,a){return a.querySelector(c)},$$child:f,$id:function(c){return b.getElementById(c)},scrollTop:function(){d.scrollTo(0,
1)},onEvent:function(c,a,g){c.addEventListener(a,g)},offEvent:function(c,a,g){c.removeEventListener(a,g)},createElement:function(c){return b.createElement(c)},showElement:function(c){c.style.display="block"},hideElement:function(c){c.style.display="none"},override:function(c,a){for(var g in a)c[g]=a[g];return c},replaceAll:function(c,a,g){return c.split(a).join(g)},windowOpen:function(c,a){return d.open(c,a)},typeCast:e,makeQueryString:function(c){var a="",g="",b;for(b in c)if(c[b]){g=g+(a+b+"="+
encodeURIComponent(c[b]));a="&"}return g},parseQueryString:function(c){var c=c.replace(/^\#/,"").replace(/^\?/,""),c=c.split("&"),a,b,d={};for(a=c.length;a--;){b=c[a].split("=");d[b[0]]=e(decodeURIComponent(b[1]))}return d}}})(window,document);
Global.Ajax=function(){var d=new XMLHttpRequest;return{request:function(b){var f=b.url,e=b.callback;b.cash||(f=f.match(/\?/)?f+"&":f+"?",f+="ajaxcash"+Date.now()+"=0");d=new XMLHttpRequest;d.onload=function(){e(d.responseText)};d.open("GET",f);d.send(null)},abort:function(){d.abort()}}};
Global.CanvasImage=function(d){var b=Global.utility.createElement,f=d.src,e=d.width,c=d.height,a=d.onload,g=b("img"),h=b("canvas");g.onload=function(){h.width=e;h.height=c;h.getContext("2d").drawImage(g,0,0);a(h,g)};g.src=f;return h};
Global.CanvasRender=function(d){var b=d.canvas,f=b.getContext("2d"),e=b.width,c=b.height,a,g,h,k={setSize:function(a){a.width&&(e=a.width,b.width=e);a.height&&(c=a.height,b.height=c)},draw:function(b){f.clearRect(0,0,e,c);a=0;for(g=b.length;a<g;a++)h=b[a],f.drawImage(h.image,h.x,h.y)}};k.setSize(d);return k};
Global.DataStore=function(d){var b=Global.DataStore,f=Global.utility.override,e,d=f({single:!1},d);if(d.single&&b.instance)return b.instance;e={};f={setData:function(c,a){e[c]=a;return!0},getData:function(c){if(c)return e[c];var c={},a;for(a in e)c[a]=e[a];return c},removeData:function(c){if(!e[c])return!1;delete e[c];return!0},resetData:function(){e={};return!0}};d.single&&(b.instance=f);return f};
Global.Event=function(d){var b=Global.Event,f=Global.utility.override,d=f({single:!1,isMobile:function(){return!1}},d);if(d.single&&b.instance)return b.instance;f={click:"click",mousedown:"mousedown",mousemove:"mousemove",mouseup:"mouseup",touchstart:"touchstart",touchmove:"touchmove",touchend:"touchend",switchclick:"touchstart",switchdown:"touchstart",switchmove:"touchmove",switchup:"touchend"};d.isMobile()||(f.switchclick="click",f.switchdown="mousedown",f.switchmove="mousemove",f.switchup="mouseup");
d.single&&(b.instance=f);return f};
Global.ExternalInterface=function(d){var b=!1,f=null,e=null,c=new Global.HashController;d||(d={});d.android?(b=!0,f=d.android,Global.EXTERNAL={}):e={};return function(){var a;a=b?{call:function(a){f[a.mode](c.makeHash(a))},addCallback:function(a,b){Global.EXTERNAL[a]=function(a){a=c.parseHash(a);return b(a.vars)}},removeCallback:function(a){delete Global.EXTERNAL[a]}}:{call:function(a){c.setHash(a)},addCallback:function(a,b){e[a]=function(){var d=c.getHash();if(d.mode===a){b(d.vars);return true}return false};
window.addEventListener("hashchange",e[a])},removeCallback:function(a){window.removeEventListener("hashchange",e[a]);delete e[a]}};a.isAndroid=function(){return b};return a}()};Global.Facebook=function(){var d=Global.utility.makeQueryString;return{getShareURL:function(b){var f="https://www.facebook.com/dialog/feed?app_id="+b.app_id+"&redirect_uri="+b.redirect_uri;return f+=d({link:b.link,picture:b.picture,name:b.name,caption:b.caption,description:b.description})}}};
Global.FPS=function(d){function b(){l++;l===q&&(l=0,f());1===j&&p(b)}function f(){m=Date.now();h=Math.round(1E3/(m-o));o=m;n.enter()}var e=Global.FPS,c=Global.utility,a=c.override,d=a({single:!1,criterion:20},d);if(d.single&&e.instance)return e.instance;var c=c.win,g=d.criterion,h=g,k=d.enterframe,i=Math.round(1E3/g),o,m,j,n={getCriterion:function(){return g},getSurver:function(){return h},getFrameTime:function(){return i},enter:function(){k({criterion:g,surver:h})},start:function(){o=Date.now();
p?(j=1,b()):j=setInterval(f,i)},stop:function(){clearInterval(j);j=0}},l=0,q=Math.round(60/g)+1,p=c.requestAnimationFrame||c.webkitRequestAnimationFrame||c.mozRequestAnimationFrame||c.oRequestAnimationFrame||c.msRequestAnimationFrame||!1;d.single&&(e.instance=n);return n};
Global.HashController=function(){var d=Global.utility.typeCast,b={makeHash:function(b){var d="#"+b.mode,b=b.vars,c="?",a;for(a in b)d+=c+a+"="+JSON.stringify(b[a]),c="&";return encodeURI(d)},setHash:function(d){location.hash=b.makeHash(d);return!0},parseHash:function(b){var e,c=null;e=decodeURIComponent(b).split("#")[1];if(!e)return!1;e=e.split("?");b=e[0];if(e[1]){c={};e=e[1].split("&");var a,g;for(g=e.length;g--;)if(e[g]){a=e[g].split("=");var h=c,k=a[0];a=a[1];var i=d(a);a=a===i&&a.match("^[\"'](.*)[\"']$")?
a.match("^[\"'](.*)[\"']$")[1]:i;h[k]=a}return{mode:b,vars:c}}return{mode:b}},getHash:function(){return b.parseHash(location.hash)}};return b};Global.ImgLoad=function(d){function b(){g++;g>=c&&a()}var f=Global.utility.createElement,e=d.srcs,c=e.length,a=d.onload,g=0;return{start:function(){var a,d;for(d=c;d--;)a=f("img"),a.src=e[d],a.onload=b}}};Global.Loading=function(d){var b=Global.utility.win,f={onload:function(d){b.addEventListener("load",d)}};if(d&&d.onload)f.onload(d.onload);return f};
Global.LocalStorage=function(d){var b=Global.LocalStorage,f=Global.utility,e=f.override,d=e({single:!1},d);if(d.single&&b.instance)return b.instance;var c=f.win.localStorage;d.single&&(b.instance=store);return{setData:function(a,b){c.setItem(a,JSON.stringify(b));return true},getData:function(a){if(a)return JSON.parse(c.getItem(a));var a={},b;for(b in c)a[b]=JSON.parse(c[b]);return a},removeData:function(a){if(!c.getItem(a))return false;c.removeItem(a);return true},resetData:function(){c.clear();return true}}};
Global.Mobile=function(){function d(a){a.preventDefault();return!1}function b(a,b){a=a?a:k;return a.match(b)?!0:!1}var f=Global.utility,e=f.win,c=f.doc,a=f.onEvent,g=f.offEvent,h=f.scrollTop,k=navigator.userAgent,i={isAndroid:function(a){return b(a,/Android/i)},isIOS:function(a){return b(a,/iPhone|iPad|iPod/i)},isWindows:function(a){return b(a,/IEMobile/i)},isMobile:function(){return i.isAndroid()||i.isIOS()||i.isWindows()},killScroll:function(){h();a(c,"touchmove",d)},revivalScroll:function(){h();
g(c,"touchmove",d)},hideAddress:function(){function b(){0===e.pageYOffset&&h()}function c(){setTimeout(b,100)}a(e,"load",c,!1);a(e,"orientationchange",c,!1)},orientationCheck:function(){return 90!==Math.abs(e.orientation)&&e.innerWidth<e.innerHeight?{portrait:!0,landscape:!1}:{portrait:!1,landscape:!0}},orientationChange:function(b){function c(a,b){a(e,"load",b);a(e,"orientationchange",b);a(e,"resize",b)}function d(){f();c(g,d)}function f(){if(i.orientationCheck().portrait)return b.portrait(),!0;
b.landscape()}b.immediately&&f();if(b.one)return c(a,d),function(){c(g,d)};c(a,f);return function(){c(g,f)}}};return i};Global.NumberImage=function(d){var b=d.type;b||(b="");return{make:function(d){var d=(""+d).split(""),e="",c;for(c=d.length;c--;)e='<span class="num_'+b+d[c]+'">&nbsp;</span>'+e;return e}}};
Global.Observer=function(d){var b=Global.Observer,f=Global.utility.override,d=f({single:!1},d);if(d.single&&b.instance)return b.instance;var e={},c={getObserved:function(){return e},on:function(a,b){e[a]||(e[a]=[]);e[a].push(b)},forOn:function(a){for(var b in a)c.on(b,a[b])},one:function(a,b){wrapfunc=function(d){b(d);c.off(a,wrapfunc)};c.on(a,wrapfunc)},off:function(a,b){if(!b)return delete e[a],!0;var c=e[a],d;if(!c)return!1;for(d=c.length;d--;)if(b===c[d])return c.splice(d,1),0===c.length&&delete e[a],
!0;return!1},forOff:function(a){for(var b in a)c.off(b,a[b])},fire:function(a,b){var c=e[a],d,f;if(!c)return!1;for(f=c.length;f--;)(d=c[f])&&d(b);return!0}};d.single&&(b.instance=c);return c};
Global.PreRender=function(d){function b(){j=Date.now();n=j-l;l=j;if(n<o&&(h--,1>h)){clearInterval(m);for(var b=g.length;b--;)a(g[b]);k()}}var f=Global.utility,e=f.override,d=e({elements:[],guesslimit:30,looptime:100,loopblur:20,onrendered:function(){}},d),c=f.showElement,a=f.hideElement,g=d.elements,h=d.guesslimit,k=d.onrendered,i=d.looptime,o=i+d.loopblur,m,j,n,l;return{start:function(){var a;for(a=g.length;a--;)c(g[a]);l=Date.now();m=setInterval(b,i)}}};
Global.Surrogate=function(d){var b=d.delay,f=d.callback,e,c,a={request:function(d){e=d;a.clear();c=setTimeout(a.flush,b)},flush:function(){f(e)},clear:function(){clearInterval(c)}};return a};
Global.Timer=function(d){function b(){j=Date.now();var c=a-(j-m)/1E3;0>c&&(c=0);l=f(c);k(l);if(j>n)return p.stop(),i(),!0;q=setTimeout(b,h);return!1}function f(a){var b;b=(""+a).split(".");a=b[0];b=b[1]?b[1]:"";a=e({num:a,digit:o.integer});b=e({num:b,digit:o.few,isFew:!0});return a+"."+b}function e(a){var b=""+a.num,d=a.digit,e=d-b.length;return!a.isFew?-1<e?c(e,0)+b:c(d,9):0<e?b+c(e,0):b.slice(0,d)}function c(b,a){for(var c="",a=""+a;0<b;)c+=a,b--;return c}var a=d.limit,g=1E3*a,h=1E3*d.interval,
k=d.onupdate,i=d.ontimeup,o=function(a){a=a.split(".");return{integer:a[0].length,few:a[1].length}}(d.template),m=0,j=0,n=g,l=f(a),q,p={getLimit:function(){return a},getTime:function(){return l},getProgress:function(){return 1-(n-j)/g},setUpdate:function(a){k=a},setTimeup:function(a){i=a},countDown:function(){j=m=Date.now();n=m+g;b()},stop:function(){clearInterval(q)}};return p};
Global.Twitter=function(){var d=Global.utility.makeQueryString;return{getShareURL:function(b){var f=b.redirect_uri,e=b.caption||"",c=b.name||"",b=b.hash||"";c&&(c=" \u300c"+c+"\u300d");b&&(b=" "+b);return f="https://twitter.com/intent/tweet?"+d({url:f,text:e+c+b})}}};
Global.XML=function(d){var b=Global.utility,f=b.$child,e=b.$$child,c=b.createElement("div"),a,b={getData:function(){return a},setData:function(b){a=c.innerHTML=b},$:function(a){return f(a,c)},$$:function(a){return e(a,c)}};d&&d.data&&b.setData(d.data);return b};
