/*! cir.js v0.8.7 | (c) 2013 Atsushi Mizoue. */(function(){
function f(a){return function(){return this[a]}}function j(a){return"cubic-bezier("+a+")"}function aa(a,b){for(var c=k("p"),d=l,e,g=m,h=a.length,r,s=RegExp("^(.*?)"+a[0]+"$","i");h--;)if(c.style[a[h]]!==n){d=p;(e=a[h].match(s)[1])?(g=e.toLowerCase(),b=g+b,g="-"+g+"-"):b=b.toLowerCase();c=q(ba("head"),k("style",{type:"text/css"}));r=c.sheet;break}return{ka:b,ua:d,prefix:e,ia:g,sheet:r}}function t(a){return u.JSON.parse(a)}function ca(a){return u.JSON.stringify(a)}
function da(a){a=a||m;a=m+a;return a.match(/^(.*?)([0-9\.]+)(.*)$/)}function v(){return Date.now()}function w(){u.scrollTo(0,1)}function x(a,b){for(var c in b)a[c]=b[c];return a}function ea(a){var b=m+a;return b.match("^{.*}$")?t(b):b.match("^[0-9.]+$")?1*b:"true"===b?p:"false"===b?l:a}function fa(a,b,c){return a.split(b).join(c)}function ha(a){var b=m,c=m,d;for(d in a)a[d]&&(c+=b+d+"="+encodeURIComponent(a[d]),b="&");return c}
function y(a,b){return Object.prototype.toString.call(b)==="[object "+a+"]"?p:l}function ia(a){return y("Object",a)}function z(a){return y("Number",a)}function ja(a){return y("String",a)}function A(a){return y("Function",a)}function ka(a){return y("Boolean",a)}function la(a){return y("Array",a)}function ma(a){return!y("Undefind",a)}function na(){return"ontouchstart"in u}function B(){}function oa(a){a.preventDefault();return l}function D(a,b){b=b||navigator.userAgent;return!!b.match(a)}
function E(a,b){return function(){return b.apply(a,arguments)}}function pa(a,b,c){b=b||a;c=c||b;for(i in b)A(b[i])&&(c[i]=E(a,b[i]));x(a,c);return c}function ba(a){return F.querySelector(a)}function qa(a,b){var c=b.querySelectorAll(a),d=[];d.push.apply(d,c);return d}function G(a,b){for(var c=a.className,c=c?c.split(" "):[],d=c.length;d--;)if(b===c[d])return p;return l}function H(a,b){if(!G(a,b)){var c=m,d=a.className;d&&(c=" ");a.className=d+c+b}}
function I(a,b){if(G(a,b)){var c,d=[],e;c=a.className.split(" ");for(e=c.length;e--;)b!==c[e]&&d.push(c[e]);a.className=d.join(" ")}}function ra(a,b){if(G(a,b))return I(a,b);H(a,b)}function sa(a,b,c){var d;if(ia(b)){for(d in b)a.setAttribute(d,b[d]);return p}return c||c===m?a.setAttribute(b,c):a.getAttribute(b)}function ta(a,b){a.removeAttribute(b)}function k(a,b){var c=F.createElement(a);b&&sa(c,b);return c}function J(a,b,c){a.addEventListener(b,c,l)}
function K(a,b,c){a.removeEventListener(b,c,l)}function ua(a){a.style.display="block"}function va(a){a.style.display="none"}function wa(a,b){a.style.opacity=b}function L(a,b){var c=a.style,d,e,g;for(d in b)e=d,g=b[d],z(g)&&(g+="px"),c[e]=g}function xa(a){return F.defaultView.getComputedStyle(a,N)}function ya(a){return a.parentNode}function q(a,b){return a.appendChild(b)}function za(a,b){return ya(a).insertBefore(b,a)}function Aa(a,b){return ya(a).insertBefore(b,a.nextSibling)}
function Ba(a){return ya(a).removeChild(a)}function Ca(a,b){if(!b)return a.innerHTML;a.innerHTML=b}function Da(a,b){for(var c=[],d=p;d;)a[b]&&c[c.length-1]!==a[b]&&c.push(a[b]),a._superclass&&a._superclass.prototype?a=a._superclass.prototype:d=l;return c}function Ea(a,b,c){return O.klass({extend:a,init:b,prop:c})}function P(a,b){return Ea(O.Base,a,b)}
function Fa(a){var b=k(a.type);b.controls=a.controls?p:l;b.preload=a.preload||"auto";b.autoplay=a.autoplay?p:l;b.loop=a.loop?p:l;b.src=a.dir+a.name+"."+a.suffix[0][0];return b}function Ga(a,b){if(!u["HTML"+a+"Element"])return l;a=a.toLowerCase();for(var c=k(a),d=[],e=0,g=b.length;e<g;e++)c.canPlayType(a+"/"+b[e][1])&&d.push(b[e]);return d.length?d:l}
var u=window,F=document,p=!0,l=!1,N=null,m="",Q={},n=void 0,R=na(),S,Ha="orientationchange",Ia=j("0.19,1,0.22,1"),T=1.70158,O=C={},Ja,Ka,La,Pa,U,Ra,Sa,Ta;Date.now||(Date.now=function(){return 1*new Date});
O.util={win:u,doc:F,pageTop:w,override:x,replaceAll:fa,template:function(a,b){for(var c in b)a=fa(a,"<%= "+c+" %>",b[c]);return a},windowOpen:function(a,b,c){var d,e=[];for(d in c)ka(c[d])&&(c[d]===p?c[d]="yes":c[d]===l&&(c[d]="no")),e.push(d+"="+c[d]);return u.open(a,b,e.join(","))},typeCast:ea,makeQueryString:ha,parseQueryString:function(a){a=a.replace(/^[\#\?]/,m);a=a.split("&");for(var b=a.length,c,d={};b--;)c=a[b].split("="),d[c[0]]=ea(decodeURIComponent(c[1]));return d},is:y,isObject:ia,isNumber:z,
isString:ja,isFunction:A,isBoolean:ka,isArray:la,isDefined:ma,isTouchable:na,nullFunction:B,eventPrevent:oa,eventStop:function(a){a.stopPropagation();return l},checkUserAgent:D,proxy:E,owner:pa};
O.dom={$:ba,$$:function(a){return qa(a,F)},$child:function(a,b){return b.querySelector(a)},$$child:qa,$id:function(a){return F.getElementById(a)},on:J,off:K,create:k,show:ua,hide:va,opacity:wa,hasClass:G,addClass:H,removeClass:I,toggleClass:ra,css:L,computedStyle:xa,append:q,parent:ya,before:za,after:Aa,remove:Ba,attr:sa,removeAttr:ta,html:Ca};
O.klass=function(a){function b(){for(var a=Da(this,"__init__"),b=a.length;b--;)a[b].apply(this,arguments)}var c=a.init||function(){},d=a.prop;(a=a.extend)&&O.extend(b,a);b.prototype.__init__=c;x(b.prototype,d);return b};O.klass.ancestors=Da;O.extend=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;var d=a.prototype;d._superclass=b;d._super=function(){var a=this.Ea,a=a?a.prototype._superclass:this.Ea=b;a.apply(this,arguments)}};
O.Base=Ea(n,function(){this.t={}},{H:0,dispose:function(){for(var a=Da(this,"disposeInternal"),b=0,c=a.length;b<c;b++)a[b].call(this);for(b in this.t)K.apply(N,this.t[b]);for(b in this)this[b]&&A(this[b].dispose)&&this[b].dispose();this.__proto__=N;for(b in this)this[b]=N,delete this[b];return N},contract:function(a,b,c){J(a,b,c);this.H++;this.t[this.H]=[a,b,c];return this.H},uncontract:function(a){if(a){var b=this.t[a];delete this.t[a];K(b[0],b[1],b[2])}}});
S=P(n,{SWITCHCLICK:R?"touchstart":"click",SWITCHDOWN:R?"touchstart":"mousedown",SWITCHMOVE:R?"touchmove":"mousemove",SWITCHUP:R?"touchend":"mouseup",SWITCHOVER:R?"touchstart":"mouseover",SWITCHOUT:R?"touchend":"mouseout",LOAD:"load",CHANGE:"change",CLICK:"click",MOUSEDOWN:"mousedown",MOUSEMOVE:"mousemove",MOUSEUP:"mouseup",MOUSEOVER:"mouseover",MOUSEOUT:"mouseout",TOUCHSTART:"touchstart",TOUCHMOVE:"touchmove",TOUCHEND:"touchend",RESIZE:"resize"});O.Event=S;S=O.e=new S;
O.ease={linear:function(a,b,c,d){return c*a/d+b},inCubic:function(a,b,c,d){return c*Math.pow(a/d,3)+b},outCubic:function(a,b,c,d){return c*(Math.pow(a/d-1,3)+1)+b},inOutCubic:function(a,b,c,d){return 1>(a/=d/2)?c/2*Math.pow(a,3)+b:c/2*(Math.pow(a-2,3)+2)+b},inQuart:function(a,b,c,d){return c*Math.pow(a/d,4)+b},outQuart:function(a,b,c,d){return-c*(Math.pow(a/d-1,4)-1)+b},inOutQuart:function(a,b,c,d){return 1>(a/=d/2)?c/2*Math.pow(a,4)+b:-c/2*(Math.pow(a-2,4)-2)+b},inQuint:function(a,b,c,d){return c*
Math.pow(a/d,5)+b},outQuint:function(a,b,c,d){return c*(Math.pow(a/d-1,5)+1)+b},inOutQuint:function(a,b,c,d){return 1>(a/=d/2)?c/2*Math.pow(a,5)+b:c/2*(Math.pow(a-2,5)+2)+b},inSine:function(a,b,c,d){return c*(1-Math.cos(a/d*(Math.PI/2)))+b},outSine:function(a,b,c,d){return c*Math.sin(a/d*(Math.PI/2))+b},inOutSine:function(a,b,c,d){return c/2*(1-Math.cos(Math.PI*a/d))+b},inExpo:function(a,b,c,d){return c*Math.pow(2,10*(a/d-1))+b},outExpo:function(a,b,c,d){return c*(-Math.pow(2,-10*a/d)+1)+b},inOutExpo:function(a,
b,c,d){return 1>(a/=d/2)?c/2*Math.pow(2,10*(a-1))+b:c/2*(-Math.pow(2,-10*--a)+2)+b},inCirc:function(a,b,c,d){return c*(1-Math.sqrt(1-(a/=d)*a))+b},outCirc:function(a,b,c,d){return c*Math.sqrt(1-(a=a/d-1)*a)+b},inOutCirc:function(a,b,c,d){return 1>(a/=d/2)?c/2*(1-Math.sqrt(1-a*a))+b:c/2*(Math.sqrt(1-(a-=2)*a)+1)+b},inQuad:function(a,b,c,d){return c*(a/=d)*a+b},outQuad:function(a,b,c,d){return-c*(a/=d)*(a-2)+b},inOutQuad:function(a,b,c,d){return 1>(a/=d/2)?c/2*a*a+b:-c/2*(--a*(a-2)-1)+b},inBack:function(a,
b,c,d){return c*(a/=d)*a*((T+1)*a-T)+b},outBack:function(a,b,c,d){return c*((a=a/d-1)*a*((T+1)*a+T)+1)+b},inOutBack:function(a,b,c,d){return 1>(a/=d/2)?c/2*a*a*(((T*=1.525)+1)*a-T)+b:c/2*((a-=2)*a*(((T*=1.525)+1)*a+T)+2)+b}};
O.cssease={linear:"linear",inCubic:j("0.55,0.055,0.675,0.19"),outCubic:j("0.215,0.61,0.355,1"),inOutCubic:j("0.645,0.045,0.355,1"),inQuart:j("0.895,0.03,0.685,0.22"),outQuart:j("0.165,0.84,0.44,1"),inOutQuart:j("0.77,0,0.175,1"),inQuint:j("0.755,0.05,0.855,0.06"),outQuint:j("0.23,1,0.32,1"),inOutQuint:j("0.86,0,0.07,1"),inSine:j("0.47,0,0.745,0.715"),outSine:j("0.39,0.575,0.565,1"),inOutSine:j("0.445,0.05,0.55,0.95"),inExpo:j("0.95,0.05,0.795,0.035"),outExpo:j("0.19,1,0.22,1"),inOutExpo:j("1,0,0,1"),
inCirc:j("0.6,0.04,0.98,0.335"),outCirc:j("0.075,0.82,0.165,1"),inOutCirc:j("0.785,0.135,0.15,0.86"),inQuad:j("0.55,0.085,0.68,0.53"),outQuad:j("0.25,0.46,0.45,0.94"),inOutQuad:j("0.455,0.03,0.515,0.955"),inBack:[j("0.6,0,0.735,0.045"),j("0.6,-0.28,0.735,0.045")],outBack:[j("0.175,0.885,0.32,1"),j("0.175,0.885,0.32,1.275")],inOutBack:[j("0.68,0,0.265,1"),j("0.68,-0.55,0.265,1.55")]};var Ua=aa(["animation","webkitAnimation"],"Animation"),Va=Ua.ua,Wa=Ua.prefix,Xa=Ua.ia,Ya=Ua.ka,V=Ua.sheet,W;
W=O.Animation=P(function(a,b,c){c=c||Q;this.r=c.onComplete||B;this.b=a;W.id++;this.d="ciranim"+W.id;a=c.duration||W.duration;var d=c.ease||Ia,e,g={};for(e in b)g[e]=b[e],z(g[e])&&(g[e]+="px");this.j=g;g=fa(fa(ca(g),'"',m),",",";");V.insertRule("@"+Xa+"keyframes "+this.d+"{to"+g+"}",V.cssRules.length);la(d)||(d=[d]);b=this.d;e=0;for(var g=d.length,h=m;e<g;e++)h+=Xa+"animation:"+b+" "+a+"ms "+d[e]+" 0s 1 normal both;";V.insertRule("."+b+"{"+h+"}",V.cssRules.length);c.manual||this.start()},{aa:function(){K(this.b,
Ya+"End",this.Y);K(this.b,"animationend",this.Y)},disposeInternal:function(){this.stop()},start:function(){function a(a){var d=V.cssRules,e=d.length,g;b.aa();if("webkit"===Wa){for(;e--;)g=d[e].name||(m+d[e].selectorText).split(".")[1],g===b.d&&V.deleteRule(e);I(b.b,b.d);L(b.b,b.j)}b.r(a)}var b=this;b.Y=a;J(b.b,Ya+"End",a);J(b.b,"animationend",a);H(b.b,b.d)},stop:function(){var a={};a[Xa+"animation-play-state"]="paused";L(this.b,a);this.aa()}});W.id=0;W.duration=500;W.support=Va;
var Za=aa(["transitionProperty","webkitTransitionProperty"],"Transition"),$a=Za.ua,ab=Za.ia,bb=Za.ka,cb=Za.sheet,X;
X=O.Transition=P(function(a,b,c){c=c||Q;X.id++;this.d="cirtrans"+X.id;var d=[];x({},b);var e,g=c.duration||X.duration,h=c.ease||Ia;la(h)||(h=[h]);for(e in b)d.push(e);e=0;for(var r=h.length,s=m,s=s+(ab+"transition-property:"+d.join(" ")+";"+ab+"transition-duration:"+g+"ms;");e<r;e++)s+=ab+"transition-timing-function:"+h[e]+";";cb.insertRule("."+this.d+"{"+s+"}",cb.cssRules.length);this.b=a;this.j=b;this.r=c.onComplete||B;c.manual||this.start()},{disposeInternal:function(){this.stop()},start:function(){var a=
this;a.B=function(b){a.stop();setTimeout(function(){a.r(b)},1)};J(a.b,bb+"End",a.B);J(a.b,"transitionend",a.B);H(a.b,a.d);L(a.b,a.j)},stop:function(){var a=cb.cssRules,b=a.length,c;K(this.b,bb+"End",this.B);K(this.b,"transitionend",this.B);for(I(this.b,this.d);b--;)if(c=a[b].name||(m+a[b].selectorText).split(".")[1],c===this.d){cb.deleteRule(b);break}}});X.id=0;X.support=$a;X.duration=500;
U=O.Tweener=P(function(a,b,c){var d;c=c||{};this.ga=a;this.j=[];for(d in b)a=b[d],a.name=d,a.La=a.to-a.from,a.prefix=a.prefix||m,a.suffix=a.suffix||"px",this.j.push(a);this.X=c.duration||U.duration;this.Ma=c.ease||this.Aa;this.r=c.onComplete;c.manual||this.start()},{disposeInternal:function(){this.stop()},Aa:function(a,b,c,d){return c*(-Math.pow(2,-10*a/d)+1)+b},ca:u.requestAnimationFrame?function(a){requestAnimationFrame(a)}:u.webkitRequestAnimationFrame?function(a){webkitRequestAnimationFrame(a)}:
u.mozRequestAnimationFrame?function(a){mozRequestAnimationFrame(a)}:u.oRequestAnimationFrame?function(a){oRequestAnimationFrame(a)}:u.msRequestAnimationFrame?function(a){msRequestAnimationFrame(a)}:function(a){setTimeout(a,1E3/U.Za)},loop:function(){for(var a=this,b=U.G,c,d=v(),e,g=b.length,h;g--;)if(c=b[g],i=c.j.length,e=d-c.Ia,e<c.X)for(;i--;)h=c.j[i],U.da(c.ga,h,c.Ma(e,h.from,h.La,c.X));else{for(;i--;)h=c.j[i],U.da(c.ga,h,h.to);c.r&&c.r();b.splice(g,1)}b.length?a.ca(function(){a.loop()}):this.stop()},
start:function(){var a=this;a.Ia=v();U.G.push(a);U.S||(U.S=1,a.ca(function(){a.loop()}))},stop:function(){U.G=[];clearInterval(U.S);U.S=N}});U.da=function(a,b,c){a[b.name]=b.prefix+c+b.suffix};U.G=[];U.fps=30;U.duration=500;O.$=function(a,b,c,d,e){function g(){}g.prototype=O.$.qa;ja(a)?(b=b||F,c=b.querySelectorAll(a)):(c=[a],a=m);e=c.length;d=new g;for(d.length=e;e--;)d[e]=c[e];return d};function Y(a,b,c){var d=a.length;for(c=db(c);d--;)c[0]=a[d],b.apply(a,c);return a}
function Z(a,b,c){c=db(c);c[0]=a[0];return b.apply(N,c)}function db(a){var b=[N];b.push.apply(b,a);return b}
O.$.qa={Ba:Y,Wa:Z,Va:db,querySelectorAll:function(a){return this[0].querySelectorAll(a)},find:function(a){return O.$(a,this.Ya)},parent:function(){return O.$(ya(this[0]))},on:function(){return Y(this,J,arguments)},off:function(){return Y(this,K,arguments)},show:function(){return Y(this,ua)},hide:function(){return Y(this,va)},opacity:function(){return Y(this,wa,arguments)},hasClass:function(){return Z(this,G,arguments)},addClass:function(){return Y(this,H,arguments)},removeClass:function(){return Y(this,
I,arguments)},toggleClass:function(){return Y(this,ra,arguments)},css:function(){return Y(this,L,arguments)},html:function(){return Z(this,Ca,arguments)},attr:function(){return Z(this,sa,arguments)},removeAttr:function(){return Y(this,ta,arguments)},append:function(){return Y(this,q,arguments)},before:function(){return Z(this,za,arguments)},after:function(){return Z(this,Aa,arguments)},remove:function(){return Y(this,Ba,arguments)}};
function eb(a,b,c,d,e){A(c)&&(e=c,c=N);A(d)&&!e&&(e=d,d=N);d&&(d=fb[d]);c={duration:c,ease:d,onComplete:e};if(gb)b=new hb(a,b,c);else{d=O.Tweener;e=a.style;var g;a=xa(a);var h,r,s={};for(g in b)h=da(b[g]),r=a.getPropertyValue(g),r=!r||"none"===r?0:1*da(r)[2],s[g]={from:r,to:1*h[2]||0,prefix:h[1],suffix:h[3]};b=new d(e,s,c)}this.o.push(b)}var ib=O.$.qa,hb=O.Animation||{},gb=hb.support,fb={};gb&&O.cssease?fb=O.cssease:O.ease&&(fb=O.ease);
ib.animate=function(){this.o||(this.o=[]);return ib.Ba(this,eb,arguments)};ib.stop=function(){if(this.o){for(var a=this.o.length;a--;)this.o[a].stop();this.o=N}return this};
O.HashQuery=P(n,{typeCast:function(a){var b=ea(a);return a===b&&(a=a.match("^[\"'](.*)[\"']$"))?a[1]:b},makeHash:function(a){var b="#"+a.mode;a=a.vars;var c="?",d;for(d in a)b+=c+d+"="+ca(a[d]),c="&";return encodeURI(b)},setHash:function(a){location.hash=this.makeHash(a)},parseHash:function(a){var b,c,d,e;b=decodeURIComponent(a).split("#")[1];if(!b)return l;b=b.split("?");a=b[0];if(b[1]){c={};b=b[1].split("&");for(e=b.length;e--;)b[e]&&(d=b[e].split("="),c[d[0]]=this.typeCast(d[1]))}return{mode:a,
vars:c}},getHash:function(){return this.parseHash(location.hash)}});
Pa=P(function(a){var b=this,c=a.autoplay,d=a.loop,e,g=a.el||F.body;a.preload="auto";a.autoplay=a.loop=l;switch(a.type){case "Audio":e=O.Audio(a);break;default:e=O.Video(a)}if(b.i=e){if(c){var h;h=this.contract(e,"canplay",function(){b.uncontract(h);b.play()})}d&&this.loop(p);a.oncanplay&&this.contract(e,"canplay",a.oncanplay);a.onended&&this.contract(e,"ended",a.onended);q(g,e)}},{disposeInternal:function(){Ba(this.i)},getElement:f("i"),getCurrent:function(){return this.i.currentTime},getDuration:function(){return this.i.duration},
setCurrent:function(a){this.i.currentTime=a},loop:function(a){var b=this;b.h&&(b.uncontract(b.h),delete b.h);a&&(b.h=b.contract(b.i,"ended",function(){b.stop();b.play()}))},play:function(){this.i.play()},pause:function(){this.i.pause()},stop:function(){this.setCurrent(0);this.pause()}});O.Audio=function(a){a.type="audio";a.suffix=O.Audio.support;return Fa(a)};O.Audio.support=Ga("Audio",[["mp3","mpeg"],["wav","wav"],["ogg","ogg"],["m4a","mp4"]]);O.Sound=function(a){a.type="Audio";return new Pa(a)};
O.Sound.support=O.Audio.support;O.Video=function(a){a.type="video";a.suffix=O.Video.support;return Fa(a)};O.Video.support=Ga("Video",[["webm","webm"],["mp4","mp4"],["ogv","ogg"]]);O.Movie=function(a){a.type="Video";return new Pa(a)};O.Movie.support=O.Video.support;
O.Ajax=P(function(a){a&&this.request(a)},{request:function(a){if("json"===a.dataType)return delete a.dataType,this.$a(a);var b=a.url,c=a.callback||B,d=a.error||B,e=a.type||"GET",g=m,h=this.va=new XMLHttpRequest;a.cash||(a.query||(a.query={}),a.query["cir"+v()]="0");a.query&&(g=a.query,ia(g)&&(g=encodeURI(ha(g))));h.onreadystatechange=function(){if(4==h.readyState){if(200==h.status)return c(h.responseText,h);d(h)}};"GET"===e&&(b=-1!==b.indexOf("?")?b+"&":b+"?",b+=g,g=m);h.open(e,b);"POST"===e&&h.setRequestHeader("Content-Type",
"application/x-www-form-urlencoded");h.send(g)},abort:function(){this.va&&this.va.abort()},json:function(a){var b=a.callback,c=a.error;a.callback=function(a){b(t(a))};a.error=function(a){c&&c(a)};this.request(a)}});O.Handle=P(function(a){this.a=a;this.attach()},{disposeInternal:function(){this.detach()},attach:function(){this.p(J)},detach:function(){this.p(K)},p:function(a){for(var b in this.a.events)a(this.a.el,b,this.a.events[b])}});
O.Brush=P(function(a){this.s=a.canvas;this.W=this.s.getContext("2d");this.setSize(a)},{setSize:function(a){a.width&&(this.s.width=a.width);a.height&&(this.s.height=a.height)},pigment:function(a){var b=k("canvas"),c=k("img");c.onload=function(){b.width=a.width;b.height=a.height;b.getContext("2d").drawImage(c,0,0);a.onload(b,c)};c.src=a.src;return{image:b,x:a.x||0,y:a.y||0}},pigments:function(a,b){function c(a){var c=a.onload||B;a.onload=function(a,d){c(a,d);g--;0===g&&b(h)};h[e]=d.pigment(a);g++}var d=
this,e,g=0,h={};b=b||B;for(e in a)c(a[e]);return h},draw:function(a){var b=0,c=a.length,d;for(this.W.clearRect(0,0,this.s.width,this.s.height);b<c;b++)d=a[b],this.W.drawImage(d.image,d.x,d.y)}});O.Brush.support=!!u.HTMLCanvasElement;O.Datetime=function(a){if(!a||z(a))return new Date(a);a=a.split(/[T:\-\+\/\s]/);3===a.length&&a.push(0,0,0);return new Date(1*a[0],a[1]-1,1*a[2],1*a[3],1*a[4],1*a[5])};
O.DataStore=P(function(){this.l={}},{set:function(a,b){this.l[a]=b},get:function(a){if(a)return this.l[a];a={};for(var b in this.l)a[b]=this.l[b];return a},remove:function(a){ma(this.l[a])&&delete this.l[a]},reset:function(){this.l={}}});
Ra=P(function(a){this.q=a.namespace?a.namespace+"-":m;this.g=u[a.type+"Storage"]},{set:function(a,b){this.g.setItem(this.q+a,ca(b))},get:function(a){var b={},c;if(a)return t(this.g.getItem(this.q+a));for(c in this.g)this.q?(a=c.split(this.q)[1])&&(b[a]=t(this.g[c])):b[c]=t(this.g[c]);return b},remove:function(a){a=this.q+a;ma(this.g.getItem(a))&&this.g.removeItem(a)},reset:function(){if(!this.q)return this.g.clear();for(var a in this.g)this.remove(a)}});
O.LocalStorage=function(a){a=a||{};a.type="local";return new Ra(a)};O.SessionStorage=function(a){a=a||{};a.type="session";return new Ra(a)};O.Deferred=P(function(){this.A=[]},{isResolve:function(){return!this.A},resolve:function(a){if(this.isResolve())return this;var b=this.A,c=b.length,d=0;this.A=N;for(this.data=a;d<c;++d)b[d](a);return this},done:function(a){this.A?this.A.push(a):a(this.data);return this}});
O.DragFlick=P(function(a){this.c=[];a=(this.a=a)||Q;a.manual||this.attach()},{J:function(a){return a.changedTouches?a.changedTouches[0]:a},wa:function(a){var b=this,c,d,e=l;this.c.push(this.contract(a.el,S.SWITCHDOWN,function(a){var h=b.J(a);c=h.pageX;d=h.pageY;e=p;oa(a)}),this.contract(u,S.SWITCHUP,function(g){e&&(g=b.J(g),a.callback({x:g.pageX-c,y:g.pageY-d}),e=l)}))},za:function(a){this.wa({el:a.el,callback:function(b){var c=a.boundary||0,d={change:l,top:l,right:l,bottom:l,left:l,amount:b};Math.abs(b.x)>
c&&(0<b.x?d.right=p:0>b.x&&(d.left=p),d.change=p);Math.abs(b.y)>c&&(0<b.y?d.bottom=p:0>b.y&&(d.top=p),d.change=p);a.callback(d)}})},attach:function(){function a(a,c,d){b.c.push(b.contract(a,c,function(a){d(b.J(a))}))}var b=this,c=this.a,d=c.el,e=c.start||B,g=c.move||B,h=c.end||B,r=l,s=0,M=0;c.direction&&b.za({el:d,boundary:c.boundary,callback:c.direction});a(d,S.SWITCHDOWN,function(a){r=p;s=a.pageX;M=a.pageY;e({e:a,move:{x:s,y:M}})});a(F,S.SWITCHMOVE,function(a){r&&g({e:a,move:{x:a.pageX-s,y:a.pageY-
M}})});a(F,S.SWITCHUP,function(a){r&&(h({e:a,move:{x:a.pageX-s,y:a.pageY-M}}),r=l)})},detach:function(){for(var a=this.c.length;a--;)this.uncontract(this.c[a]);this.c=[]}});O.ExternalInterface=function(a){a=a||Q;var b=La;a.android&&(b=Ka);return new b(a)};Ka=Ea(O.HashQuery,function(a){this.Ga=a.android;this.la=a.externalObj},{call:function(a){this.Ga[a.mode](this.makeHash(a))},addCallback:function(a,b){var c=this;c.la[a]=function(a){b(c.parseHash(a).vars)}},removeCallback:function(a){delete this.la[a]}});
La=Ea(O.HashQuery,function(){this.w={}},{disposeInternal:function(){for(var a in this.w)this.removeCallback(a)},call:function(a){this.setHash(a)},addCallback:function(a,b){var c=this;c.w[a]=function(){var d=c.getHash();d.mode===a&&b(d.vars)};J(u,"hashchange",c.w[a])},removeCallback:function(a){K(u,"hashchange",this.w[a]);delete this.w[a]}});
O.Facebook=P(n,{shareURL:function(a){return"https://www.facebook.com/dialog/feed?app_id="+a.app_id+"&redirect_uri="+a.redirect_uri+ha({link:a.link,picture:a.picture,name:a.name,caption:a.caption,description:a.description})}});
O.FPS=P(function(a){this.K=this.R=a.criterion;this.ra=this.Z(this.K);this.Na=a.enterframe;a.manual||this.start()},{O:0,M:0,h:0,disposeInternal:function(){this.stop()},getCriterion:f("K"),getSurver:f("R"),getFrameTime:f("ra"),enter:function(){this.Na({criterion:this.K,surver:this.R})},start:function(){this.O=v();this.h=setInterval(this.Ca,this.ra,this)},Ca:function(a){a.M=v();a.R=a.Z(a.M-a.O);a.O=a.M;a.enter()},Z:function(a){return Math.round(1E3/a)},stop:function(){clearInterval(this.h)}});
O.ImgLoad=P(function(a){this.ta=a.srcs;this.Q=this.ta.length;this.na=[];this.c=[];this.I=a.onload||B;this.Da=a.onprogress||B;a.manual||this.start()},{L:0,P:0,ya:function(){this.L++;this.P=this.L/this.Q;this.Da(this.P);if(this.L>=this.Q){for(var a=this.c.length;a--;)this.uncontract(this.c[a]);this.c=[];this.I(this.na)}},start:function(){function a(){b.ya()}if(!this.Ta){this.Ta=p;for(var b=this,c,d=b.Q;d--;)c=k("img"),c.src=b.ta[d],b.c.push(b.contract(c,S.LOAD,a)),b.na.push(c)}},getProgress:f("P")});
O.WindowLoad=P(function(a){a&&this.I(a.onload)},{I:function(a){var b=this,c;c=b.contract(u,S.LOAD,function(){b.uncontract(c);a()})}});
Sa=O.Mobile=P(n,{getZoom:function(){return F.body.clientWidth/u.innerWidth},isAndroid:function(a){return D(/Android/i,a)},isIOS:function(a){return D(/iPhone|iPad|iPod/i,a)},isWindows:function(a){return D(/IEMobile/i,a)},isFBAPP:function(a){return D(/FBAN/,a)},isMobile:function(){return this.isAndroid()||this.isIOS()||this.isWindows()||this.isFBAPP()},killScroll:function(a){this.D||(a||w(),this.D=this.contract(F,S.TOUCHMOVE,oa))},revivalScroll:function(a){this.D&&(a||w(),this.uncontract(this.D),delete this.D)},
hideAddress:function(){function a(){0===u.pageYOffset&&w()}function b(){setTimeout(a,100)}this.contract(u,S.LOAD,b,l);this.contract(u,Ha,b,l)},getOrientation:function(){return 90!==Math.abs(u.orientation)&&u.innerWidth<u.innerHeight?{portrait:p,landscape:l}:{portrait:l,landscape:p}},attachOrientation:function(a){function b(a){h.push(g.contract(u,S.LOAD,a),g.contract(u,Ha,a),g.contract(u,S.RESIZE,a))}function c(){for(var a=h.length;a--;)g.uncontract(h[a]);h=[]}function d(){e();c()}function e(){if(g.getOrientation().portrait)return a.portrait();
a.landscape()}var g=this,h=[];a.immediately&&e();if(a.one)return b(d),function(){c()};b(e);return function(){c()}}});O.mobile=new Sa;Ta=O.PC=P(n,{v:function(a,b){a||w();L(F.body,{overflow:b})},killScroll:function(a){this.v(a,"hidden")},revivalScroll:function(a){this.v(a,"auto")}});O.pc=new Ta;
O.Modal=P(function(a){this.a=a=a||Q;var b={display:"none",position:"absolute"};this.v=new (R?Sa:Ta);this.c=[];this.k=k("div",{"class":"cir-modal-bg"});L(this.k,x({zIndex:9998,top:0,left:0,width:"100%",height:"300%"},b));q(F.body,this.k);this.f=k("div",{"class":"cir-modal-content"});L(this.f,x({zindex:9999,top:"50%",left:"50%"},b));q(F.body,this.f);a.manual||this.open()},{V:function(){for(var a=this.c.length;a--;)this.uncontract(this.c[a]);this.c=[]},disposeInternal:function(){this.close();Ba(this.k);
Ba(this.f)},open:function(a){this.v.killScroll(!0);L(this.k,{top:F.body.scrollTop});ua(this.k);this.inner(a)},close:function(){this.V();Ca(this.f,"");va(this.f);va(this.k);this.v.revivalScroll(!0)},inner:function(a){this.V();a=a||this.a.html;Ca(this.f,a);ua(this.f);a=xa(this.f);L(this.f,{"margin-top":F.body.scrollTop-da(a.height)[2]/2,"margin-left":-(da(a.width)[2]/2)});this.a.bgClose&&this.contract(this.k,S.CLICK,E(this,this.close));if(this.a.closeSelector){a=qa(this.a.closeSelector,this.f);for(var b=
a.length;b--;)this.c.push(this.contract(a[b],S.CLICK,E(this,this.close)))}}});Ja=P(function(a){this.a=a;this.attach()},{attach:function(){this.detach();this.xa=this.contract(u,this.a.e,this.a.callback)},detach:function(){this.uncontract(this.xa)}});O.DeviceOrientation=function(a){a.e="deviceorientation";return Ja(a)};O.DeviceOrientation.support="ondeviceorientation"in u;O.DeviceMotion=function(a){a.e="devicemotion";return Ja(a)};O.DeviceMotion.support="ondevicemotion"in u;var jb,mb;
O.DeviceOrientation.support?(jb=O.DeviceOrientation,mb=function(a){return a}):O.DeviceMotion.support&&(jb=O.DeviceMotion,mb=function(a){return a.rotationRate});O.DeviceShake=P(function(a){this.ea=new jb;this.a=a;this.attach()},{Ja:{x:"gamma",y:"beta",z:"alpha"},attach:function(){var a=this,b,c=a.Ja[a.a.direction];a.ea.attach(function(d){d=mb(d);b||(b=d);Math.abs(d[c]-b[c])>a.a.limit&&(b=N,a.a.callback(d),setTimeout(function(){},a.a.waittime))})},detach:function(){this.ea.detach()}});
O.DeviceShake.support=jb?p:l;O.FontImg=P(function(a){a=a||Q;this.Fa=a.type?a.type+"_":m;this.fa=a.tag||"span"},{make:function(a){a=(m+a).split(m);for(var b=m,c=a.length;c--;)b="<"+this.fa+' class="font_'+this.Fa+a[c]+'"></'+this.fa+">"+b;return b}});
O.Observer=P(function(){this.N={}},{on:function(a,b){var c=this.N;c[a]||(c[a]=[]);c[a].push(b)},one:function(a,b){function c(e){b(e);d.off(a,c)}var d=this;d.on(a,c)},off:function(a,b){var c=this.N;if(!b)return delete c[a];var d=c[a],e;if(d)for(e=d.length;e--;)if(b===d[e])return d.splice(e,1),0===d.length&&delete c[a],p;return l},fire:function(a,b){var c=this.N[a],d,e;if(c)for(e=c.length;e--;)(d=c[e])&&d(b)}});
O.PreRender=P(function(a){this.n=a.els;this.ma=a.guesslimit||30;this.Sa=a.onrendered;this.pa=a.looptime||100;this.Ra=this.pa+(a.loopblur||20);a.manual||this.start()},{disposeInternal:function(){clearInterval(this.h)},start:function(){var a,b=this,c=v();for(a=b.n.length;a--;)ua(b.n[a]);b.h=setInterval(function(){var a=v(),e=a-c;c=a;if(e<b.Ra&&(b.ma--,1>b.ma)){clearInterval(b.h);for(a=b.n.length;a--;)va(b.n[a]);b.Sa()}},this.pa,this)}});
O.Route=P(function(a){this.a=a;a.manual||this.start()},{start:function(){this.fire(this.a.target)},fire:function(a){var b;if(this.a.noregex&&this.a.action[a])return this.a.action[a](a);for(b in this.a.action)if(a.match(b))this.a.action[b](b)}});
O.ScriptLoad=P(function(){this.n=[]},{requests:function(a,b){function c(c){var g=a[c].callback;a[c].callback=function(a){g(a);e--;0===e&&b(d.n)};d.request(a[c])}for(var d=this,e=0,g=a.length;e<g;e++)c(e)},request:function(a){var b=this,c=k("script"),d;c.src=a.src;q(F.body,c);b.n.push(c);a.callback&&(d=b.contract(c,S.LOAD,function(){b.uncontract(d);a.callback.apply(this,arguments)}))}});function $(a){return nb?ob.getResponseHeader(a):l}
function pb(a){var b=new XMLHttpRequest;b.onload=function(){a(b)};b.open("HEAD",location.href+"?update"+v()+"=1");b.send(N);return b}var ob,nb=l;
O.ServerMeta=P(function(a){a=a||Q;var b=a.callback||B;ob?b(ob):ob=pb(function(){nb=p;b(ob)})},{date:function(a){return pb(function(b){a(b.getResponseHeader("Date"))})},connection:function(){return $("Connection")},contentLength:function(){return $("Content-Length")},lastModified:function(){return $("Last-Modified")},server:function(){return $("Server")},contentType:function(){return $("Content-Type")},acceptRanges:function(){return $("Accept-Ranges")},keepAlive:function(){return $("Keep-Alive")}});
O.Surrogate=P(function(a){this.Ka=a.delay;this.C=a.callback},{disposeInternal:function(){this.clear()},request:function(a){this.Ha=a;this.clear();this.U=setTimeout(this.flush,this.Ka,this)},flush:function(a){a=a||this;a.C(a.Ha)},clear:function(){clearInterval(this.U)}});
O.Throttle=P(function(a){this.Ua=a.waittime;this.C=a.callback},{disposeInternal:function(){this.unlock()},request:function(a){var b=this;b.oa?b.T=a:(b.C(a),b.lock(),b.U=setTimeout(function(){b.T&&(b.C(b.T),b.T=N);b.unlock()},b.Ua,b))},lock:function(){this.oa=p},unlock:function(a){a=a||this;a.oa=l;clearInterval(a.U)}});
O.Timer=function(a){function b(){ga=v();var a=g-(ga-Na)/1E3;0>a&&(a=0);Qa=c(a);s(Qa);ga>Oa?(kb.stop(),M()):lb=setTimeout(b,r)}function c(a){var b;b=(m+a).split(".");a=b[0];b=b[1]?b[1]:m;a=d({sa:a,ja:Ma.Pa});b=d({sa:b,ja:Ma.Oa,Qa:p});return a+"."+b}function d(a){var b=m+a.sa,c=a.ja,d=c-b.length;return!a.Qa?-1<d?e(d,0)+b:e(c,9):0<d?b+e(d,0):b.slice(0,c)}function e(a,b){var c=m;for(b=m+b;0<a;)c+=b,a--;return c}var g=a.limit,h=1E3*g,r=1E3*a.interval,s=a.onupdate,M=a.ontimeup,Ma;a=a.template.split(".");
Ma={Pa:a[0].length,Oa:a[1].length};var Na=0,ga=0,Oa=h,Qa=c(g),lb,kb={getLimit:function(){return g},getTime:function(){return Qa},getProgress:function(){return 1-(Oa-ga)/h},setUpdate:function(a){s=a},setTimeup:function(a){M=a},countDown:function(){ga=Na=v();Oa=Na+h;b()},stop:function(){clearInterval(lb)}};return kb};
O.Twitter=P(n,{shareURL:function(a){var b=a.name,c=a.hash,b=b?" \u300c"+b+"\u300d":m,c=c?" "+c:m;return"https://twitter.com/intent/tweet?"+ha({url:a.redirect_uri,text:(a.caption||m)+b+c})}});O.XML=P(function(a){this.b=k("div");Ca(this.b,a.data)},{$:function(a){return this.b.querySelector(a)},$$:function(a){return qa(a,this.b)}});
O.Model=P(function(a){a=a||Q;var b,c=a.defaults||this.defaults||{},d=a.events||this.events;this.ha=a.validate||this.validate||{};this.m=a.store||this.store||new C.DataStore;this.u=new C.Observer;for(b in c)this.set(b,c[b]);for(b in d)this.on(b,d[b])},{F:function(a,b,c){this.u.fire(a,this.m.get());b&&this.u.fire(a+":"+b,c)},set:function(a,b){if(this.ha[a]&&!this.ha[a](a,b))return this.F("fail",a,b);this.ba=this.m.get();this.m.set(a,b);this.F(S.CHANGE,a,b)},prev:function(a){return!a?this.ba:this.ba[a]},
get:function(a){return this.m.get(a)},remove:function(a){if(a){var b=this.m.get(a),c=this.m.remove(a);this.F("remove",a,b);return c}},reset:function(){this.m.reset();this.F("reset")},on:function(a,b){var c=E(this,b);this.u.on(a,c);return c},off:function(a,b){this.u.off(a,b)},fire:function(a,b){return this.u.fire(a,b)}});
O.View=P(function(a){a=a?pa(this,a):pa(this,this,{});this.el=O.$(a.el||this.el||k("div"));this.attach();a.init&&this.init()},{disposeInternal:function(){this.p("off")},p:function(a){var b,c,d,e=this.events;for(b in e)for(c in d="me"===b?this.el:this.el.find(b),e[b])d[a](c,this[e[b][c]])},attach:function(){this.p("on")},detach:function(){this.p("off")}});
O.Validate=P(function(a){a=a||{};this.Xa=a.level;pa(this,this,a)},{displayError:function(a,b){b="Validate Error:"+a+" is "+b+".";switch(this.ab){case "log":return console.log(b),l;case "error":throw Error(b);case "off":return l;default:return console.warn(b),l}},isObject:function(a,b){if(ia(b))return p;this.displayError(a,"Object")},isNumber:function(a,b){if(z(b))return p;this.displayError(a,"Number")},isString:function(a,b){if(ja(b))return p;this.displayError(a,"String")},isFunction:function(a,b){if(A(b))return p;
this.displayError(a,"Function")},isBoolean:function(a,b){if(ka(b))return p;this.displayError(a,"Boolean")},isArray:function(a,b){if(la(b))return p;this.displayError(a,"Array")}});O.validate=new O.Validate;
}());
