document.write('\
<script type="text/template" id="jasmineBaseList">\
src/Ajax/\n\
src/Animation/\n\
src/Audio/\n\
src/Base/\n\
src/Brush/\n\
src/DataStore/\n\
src/Datetime/\n\
src/Deferred/\n\
src/DeviceAction/\n\
src/DeviceMotion/\n\
src/DeviceOrientation/\n\
src/DeviceShake/\n\
src/DragFlick/\n\
src/Embed/\n\
src/Event/\n\
src/ExternalInterface/\n\
src/ExternalInterface.Android/\n\
src/ExternalInterface.IOS/\n\
src/FPS/\n\
src/Facebook/\n\
src/FontImg/\n\
src/Handle/\n\
src/HashQuery/\n\
src/ImgLoad/\n\
src/LocalStorage/\n\
src/Media/\n\
src/Mobile/\n\
src/Model/\n\
src/Movie/\n\
src/Observer/\n\
src/PreRender/\n\
src/Route/\n\
src/ScriptLoad/\n\
src/ServerMeta/\n\
src/SessionStorage/\n\
src/Sound/\n\
src/Surrogate/\n\
src/Throttle/\n\
src/Timer/\n\
src/Transition/\n\
src/Tweener/\n\
src/Twitter/\n\
src/Video/\n\
src/View/\n\
src/WebStorage/\n\
src/WindowLoad/\n\
src/XML/\n\
src/cssease/\n\
src/dom/\n\
src/ease/\n\
src/extend/\n\
src/klass/\n\
src/selector/\n\
src/selector.methods/\n\
src/selector.methods.animate/\n\
src/util/\n\
</script>\
<script type="text/template" id="jasmineClassList">\
../../js/src/Ajax.js\n\
../../js/src/Animation.js\n\
../../js/src/Audio.js\n\
../../js/src/Base.js\n\
../../js/src/Brush.js\n\
../../js/src/DataStore.js\n\
../../js/src/Datetime.js\n\
../../js/src/Deferred.js\n\
../../js/src/DeviceAction.js\n\
../../js/src/DeviceMotion.js\n\
../../js/src/DeviceOrientation.js\n\
../../js/src/DeviceShake.js\n\
../../js/src/DragFlick.js\n\
../../js/src/Embed.js\n\
../../js/src/Event.js\n\
../../js/src/ExternalInterface.js\n\
../../js/src/ExternalInterface.Android.js\n\
../../js/src/ExternalInterface.IOS.js\n\
../../js/src/FPS.js\n\
../../js/src/Facebook.js\n\
../../js/src/FontImg.js\n\
../../js/src/Handle.js\n\
../../js/src/HashQuery.js\n\
../../js/src/ImgLoad.js\n\
../../js/src/LocalStorage.js\n\
../../js/src/Media.js\n\
../../js/src/Mobile.js\n\
../../js/src/Model.js\n\
../../js/src/Movie.js\n\
../../js/src/Observer.js\n\
../../js/src/PreRender.js\n\
../../js/src/Route.js\n\
../../js/src/ScriptLoad.js\n\
../../js/src/ServerMeta.js\n\
../../js/src/SessionStorage.js\n\
../../js/src/Sound.js\n\
../../js/src/Surrogate.js\n\
../../js/src/Throttle.js\n\
../../js/src/Timer.js\n\
../../js/src/Transition.js\n\
../../js/src/Tweener.js\n\
../../js/src/Twitter.js\n\
../../js/src/Video.js\n\
../../js/src/View.js\n\
../../js/src/WebStorage.js\n\
../../js/src/WindowLoad.js\n\
../../js/src/XML.js\n\
../../js/src/cssease.js\n\
../../js/src/dom.js\n\
../../js/src/ease.js\n\
../../js/src/extend.js\n\
../../js/src/klass.js\n\
../../js/src/selector.js\n\
../../js/src/selector.methods.js\n\
../../js/src/selector.methods.animate.js\n\
../../js/src/util.js\n\
</script>\
<script type="text/template" id="jasmineTestList">\
../_src/src/Ajax/test.js\n\
../_src/src/Animation/test.js\n\
../_src/src/Audio/test.js\n\
../_src/src/Base/test.js\n\
../_src/src/Brush/test.js\n\
../_src/src/DataStore/test.js\n\
../_src/src/Datetime/test.js\n\
../_src/src/Deferred/test.js\n\
../_src/src/DeviceAction/test.js\n\
../_src/src/DeviceMotion/test.js\n\
../_src/src/DeviceOrientation/test.js\n\
../_src/src/DeviceShake/test.js\n\
../_src/src/DragFlick/test.js\n\
../_src/src/Embed/test.js\n\
../_src/src/Event/test.js\n\
../_src/src/ExternalInterface/test.js\n\
../_src/src/ExternalInterface.Android/test.js\n\
../_src/src/ExternalInterface.IOS/test.js\n\
../_src/src/FPS/test.js\n\
../_src/src/Facebook/test.js\n\
../_src/src/FontImg/test.js\n\
../_src/src/Handle/test.js\n\
../_src/src/HashQuery/test.js\n\
../_src/src/ImgLoad/test.js\n\
../_src/src/LocalStorage/test.js\n\
../_src/src/Media/test.js\n\
../_src/src/Mobile/test.js\n\
../_src/src/Model/test.js\n\
../_src/src/Movie/test.js\n\
../_src/src/Observer/test.js\n\
../_src/src/PreRender/test.js\n\
../_src/src/Route/test.js\n\
../_src/src/ScriptLoad/test.js\n\
../_src/src/ServerMeta/test.js\n\
../_src/src/SessionStorage/test.js\n\
../_src/src/Sound/test.js\n\
../_src/src/Surrogate/test.js\n\
../_src/src/Throttle/test.js\n\
../_src/src/Timer/test.js\n\
../_src/src/Transition/test.js\n\
../_src/src/Tweener/test.js\n\
../_src/src/Twitter/test.js\n\
../_src/src/Video/test.js\n\
../_src/src/View/test.js\n\
../_src/src/WebStorage/test.js\n\
../_src/src/WindowLoad/test.js\n\
../_src/src/XML/test.js\n\
../_src/src/cssease/test.js\n\
../_src/src/dom/test.js\n\
../_src/src/ease/test.js\n\
../_src/src/extend/test.js\n\
../_src/src/klass/test.js\n\
../_src/src/selector/test.js\n\
../_src/src/selector.methods/test.js\n\
../_src/src/selector.methods.animate/test.js\n\
../_src/src/util/test.js\n\
</script>\
');
