document.write('\
<script type="text/template" id="jasmineBaseList">\
src/Ajax/\n\
src/Animation/\n\
src/Bind/\n\
src/CanvasImg/\n\
src/CanvasRender/\n\
src/DataStore/\n\
src/Deferred/\n\
src/DragFlick/\n\
src/Event/\n\
src/ExternalInterface/\n\
src/ExternalInterface.Android/\n\
src/ExternalInterface.IOS/\n\
src/FPS/\n\
src/Facebook/\n\
src/FontImg/\n\
src/HashController/\n\
src/ImgLoad/\n\
src/LocalStorage/\n\
src/Mobile/\n\
src/Observer/\n\
src/PreRender/\n\
src/Route/\n\
src/ScriptLoad/\n\
src/ServerMeta/\n\
src/SessionStorage/\n\
src/Surrogate/\n\
src/Throttle/\n\
src/Timer/\n\
src/Transition/\n\
src/Tweener/\n\
src/Twitter/\n\
src/WindowLoad/\n\
src/XML/\n\
src/cssease/\n\
src/ease/\n\
src/element/\n\
src/extend/\n\
src/klass/\n\
src/selector/\n\
src/selector.methods/\n\
src/selector.methods.animate/\n\
src/utility/\n\
</script>\
<script type="text/template" id="jasmineClassList">\
../../js/src/Ajax.js\n\
../../js/src/Animation.js\n\
../../js/src/Bind.js\n\
../../js/src/CanvasImg.js\n\
../../js/src/CanvasRender.js\n\
../../js/src/DataStore.js\n\
../../js/src/Deferred.js\n\
../../js/src/DragFlick.js\n\
../../js/src/Event.js\n\
../../js/src/ExternalInterface.js\n\
../../js/src/ExternalInterface.Android.js\n\
../../js/src/ExternalInterface.IOS.js\n\
../../js/src/FPS.js\n\
../../js/src/Facebook.js\n\
../../js/src/FontImg.js\n\
../../js/src/HashController.js\n\
../../js/src/ImgLoad.js\n\
../../js/src/LocalStorage.js\n\
../../js/src/Mobile.js\n\
../../js/src/Observer.js\n\
../../js/src/PreRender.js\n\
../../js/src/Route.js\n\
../../js/src/ScriptLoad.js\n\
../../js/src/ServerMeta.js\n\
../../js/src/SessionStorage.js\n\
../../js/src/Surrogate.js\n\
../../js/src/Throttle.js\n\
../../js/src/Timer.js\n\
../../js/src/Transition.js\n\
../../js/src/Tweener.js\n\
../../js/src/Twitter.js\n\
../../js/src/WindowLoad.js\n\
../../js/src/XML.js\n\
../../js/src/cssease.js\n\
../../js/src/ease.js\n\
../../js/src/element.js\n\
../../js/src/extend.js\n\
../../js/src/klass.js\n\
../../js/src/selector.js\n\
../../js/src/selector.methods.js\n\
../../js/src/selector.methods.animate.js\n\
../../js/src/utility.js\n\
</script>\
<script type="text/template" id="jasmineTestList">\
../_src/src/Ajax/test.js\n\
../_src/src/Animation/test.js\n\
../_src/src/Bind/test.js\n\
../_src/src/CanvasImg/test.js\n\
../_src/src/CanvasRender/test.js\n\
../_src/src/DataStore/test.js\n\
../_src/src/Deferred/test.js\n\
../_src/src/DragFlick/test.js\n\
../_src/src/Event/test.js\n\
../_src/src/ExternalInterface/test.js\n\
../_src/src/ExternalInterface.Android/test.js\n\
../_src/src/ExternalInterface.IOS/test.js\n\
../_src/src/FPS/test.js\n\
../_src/src/Facebook/test.js\n\
../_src/src/FontImg/test.js\n\
../_src/src/HashController/test.js\n\
../_src/src/ImgLoad/test.js\n\
../_src/src/LocalStorage/test.js\n\
../_src/src/Mobile/test.js\n\
../_src/src/Observer/test.js\n\
../_src/src/PreRender/test.js\n\
../_src/src/Route/test.js\n\
../_src/src/ScriptLoad/test.js\n\
../_src/src/ServerMeta/test.js\n\
../_src/src/SessionStorage/test.js\n\
../_src/src/Surrogate/test.js\n\
../_src/src/Throttle/test.js\n\
../_src/src/Timer/test.js\n\
../_src/src/Transition/test.js\n\
../_src/src/Tweener/test.js\n\
../_src/src/Twitter/test.js\n\
../_src/src/WindowLoad/test.js\n\
../_src/src/XML/test.js\n\
../_src/src/cssease/test.js\n\
../_src/src/ease/test.js\n\
../_src/src/element/test.js\n\
../_src/src/extend/test.js\n\
../_src/src/klass/test.js\n\
../_src/src/selector/test.js\n\
../_src/src/selector.methods/test.js\n\
../_src/src/selector.methods.animate/test.js\n\
../_src/src/utility/test.js\n\
</script>\
');
