document.write('\
<script type="text/template" id="jasmineBaseList">\
src/Ajax/\n\
src/Bind/\n\
src/CanvasImage/\n\
src/CanvasRender/\n\
src/DataStore/\n\
src/DragFlick/\n\
src/Easing/\n\
src/Event/\n\
src/ExternalAndroidInterface/\n\
src/ExternalIOSInterface/\n\
src/ExternalInterface/\n\
src/FPS/\n\
src/Facebook/\n\
src/HashController/\n\
src/ImgLoad/\n\
src/Loading/\n\
src/LocalStorage/\n\
src/Mobile/\n\
src/NumberImage/\n\
src/Observer/\n\
src/PreRender/\n\
src/ScriptLoad/\n\
src/ServerMeta/\n\
src/SessionStorage/\n\
src/Surrogate/\n\
src/Throttle/\n\
src/Timer/\n\
src/Tweener/\n\
src/Twitter/\n\
src/XML/\n\
src/extend/\n\
src/klass/\n\
src/selector/\n\
src/selector.methods/\n\
src/utility/\n\
</script>\
<script type="text/template" id="jasmineClassList">\
../../js/src/Ajax.js\n\
../../js/src/Bind.js\n\
../../js/src/CanvasImage.js\n\
../../js/src/CanvasRender.js\n\
../../js/src/DataStore.js\n\
../../js/src/DragFlick.js\n\
../../js/src/Easing.js\n\
../../js/src/Event.js\n\
../../js/src/ExternalAndroidInterface.js\n\
../../js/src/ExternalIOSInterface.js\n\
../../js/src/ExternalInterface.js\n\
../../js/src/FPS.js\n\
../../js/src/Facebook.js\n\
../../js/src/HashController.js\n\
../../js/src/ImgLoad.js\n\
../../js/src/Loading.js\n\
../../js/src/LocalStorage.js\n\
../../js/src/Mobile.js\n\
../../js/src/NumberImage.js\n\
../../js/src/Observer.js\n\
../../js/src/PreRender.js\n\
../../js/src/ScriptLoad.js\n\
../../js/src/ServerMeta.js\n\
../../js/src/LocalStorage.js\n\
../../js/src/Surrogate.js\n\
../../js/src/Throttle.js\n\
../../js/src/Timer.js\n\
../../js/src/Tweener.js\n\
../../js/src/Twitter.js\n\
../../js/src/XML.js\n\
../../js/src/extend.js\n\
../../js/src/klass.js\n\
../../js/src/selector.js\n\
../../js/src/selector.methods.js\n\
../../js/src/utility.js\n\
</script>\
<script type="text/template" id="jasmineTestList">\
../_src/src/Ajax/test.js\n\
../_src/src/Bind/test.js\n\
../_src/src/CanvasImage/test.js\n\
../_src/src/CanvasRender/test.js\n\
../_src/src/DataStore/test.js\n\
../_src/src/DragFlick/test.js\n\
../_src/src/Easing/test.js\n\
../_src/src/Event/test.js\n\
../_src/src/ExternalAndroidInterface/test.js\n\
../_src/src/ExternalIOSInterface/test.js\n\
../_src/src/ExternalInterface/test.js\n\
../_src/src/FPS/test.js\n\
../_src/src/Facebook/test.js\n\
../_src/src/HashController/test.js\n\
../_src/src/ImgLoad/test.js\n\
../_src/src/Loading/test.js\n\
../_src/src/LocalStorage/test.js\n\
../_src/src/Mobile/test.js\n\
../_src/src/NumberImage/test.js\n\
../_src/src/Observer/test.js\n\
../_src/src/PreRender/test.js\n\
../_src/src/ScriptLoad/test.js\n\
../_src/src/ServerMeta/test.js\n\
../_src/src/SessionStorage/test.js\n\
../_src/src/Surrogate/test.js\n\
../_src/src/Throttle/test.js\n\
../_src/src/Timer/test.js\n\
../_src/src/Tweener/test.js\n\
../_src/src/Twitter/test.js\n\
../_src/src/XML/test.js\n\
../_src/src/extend/test.js\n\
../_src/src/klass/test.js\n\
../_src/src/selector/test.js\n\
../_src/src/selector.methods/test.js\n\
../_src/src/utility/test.js\n\
</script>\
');
